### PR TITLE
USAGOV-106 Nav items menu block

### PR DESCRIPTION
**Pull request by cwacht**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-106

## Description

This Pull Request changes the way we render navigation items from a View Block to a Menu Block.

This effects all these areas: (in English and Spanish)
* Homepage - All topics and services cards
* Navigation pages - cards or list items
* Life events - cards
* Life events landing page - cards

Everything should look and work exactly the same as before except:
* We can add menu items that link to external pages, and they will show on nav pages
* We can add menu items that link to any of our pagetypes, and they will show on nav pages

## Changes to make after deployment
* On the Scams page, the cards will display twice until we remove the hardcoded cards
  * We are now able to create a card that links to the scams wizard
* On the About USA.gov page, we can now create a card that links directly to `/website-analytics`
  * We can get rid of the `/analytics-dashboard-redirect` page

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Comment by IsabelLaurenceau** [comment]
@cwacht any specific testing instructions you want followed for this PR?

**Comment by cwacht** [comment]
Following these steps should verify that everything is working as expected:

* Make sure the cards look OK on all 4 of the page types listed in the description.
* Add a menu item that links to an external page
  * Put it on a nav page
  * Verify that it shows up and links to the external page.
* Add a menu item that links to a page that is not a "Basic Page" (Like the Scams Wizard)
  * Put it on a nav page
  * Verify that it shows up and links to the right page
* Add a menu item that links to `/website-analytics`
  * Put it on a nav page
  * Verify that it shows up and links to `/website-analytics` (even if the page doesnt exist)

**Comment by IsabelLaurenceau** [comment]
Almost everything was working except the life-event thumbnail photos aren't showing on the life events nav page even though they show on the homepage and their individual pages. 

Screen Shot 2023-06-13 at 10 55 43 AM

Screen Shot 2023-06-13 at 10 56 21 AM
Screen Shot 2023-06-13 at 11 01 27 AM

**Review by IsabelLaurenceau — CHANGES_REQUESTED** [review]
Almost everything was working except the life-event thumbnail photos aren't showing on the life events nav page even though they show on the homepage and their individual pages. 

Screen Shot 2023-06-13 at 10 55 43 AM

Screen Shot 2023-06-13 at 10 56 21 AM
Screen Shot 2023-06-13 at 11 01 27 AM

**Comment by cwacht** [comment]
Did those images show up on your localhost before? I could not test them locally because those images never showed up on my localhost even in the dev branch. All I could do locally, is confirm that the correct image url was being applied. Can you check the image urls and confirm that they look correct?

This is one of the reasons I tested on the dev environment, and it worked when it was deployed there.

**Comment by IsabelLaurenceau** [comment]
Yeah looks to be the same case for me. Just tested on a few branches. URL looks good like you said, so I'll approve and merge this in.

**Review by IsabelLaurenceau — APPROVED** [review]

**Comment by IsabelLaurenceau** [comment]
You're getting the same lint errors that I put in chat, so I think we  have to wait for Mark to make those changes. I approved it though so you should be able to pull, merge and deploy if he does that after I sign off

**Pull request merged**
