### PR TITLE
Usagov 1791 analytics attribute

### PR DESCRIPTION
**Pull request by omerida**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-1791

## Description

Add a data attribute to links in the benefit search results so that analytics can track clicks without relying on other markup.

## Type of Changes

- [x] New Feature
- [ ] Bugfix
- [ ] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [x] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

## Testing Instructions

Need to have working benefit search result pages.
Import the new views.

### Change Requirements

- [ ] Requires New Documentation (Link: {})
- [x] Requires New Config
- [ ] Requires New Content

### Validation Steps

- On the English benefit search page, select all categories.
- Confirm life event links have markup with the data-attribute set
```
<a href="/benefit-finder/disability" data-analytics="category-results-links" hreflang="en">Benefit finder: disability</a>
```
- Confirm page links have markup with the same data-attribute
- Repeat on Spanish pages, only markup difference should be `hreflang="es"`

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

### CODE REVIEW

**Review by IsabelLaurenceau — COMMENTED** [review]
I'm not sure if I am missing a step but I didn't see any changes to the data attributes
drush cim
before
after

**Comment by omerida** [comment]
does https://localhost/_data/benefits-search/en/pages.json look like:

[image: image.png]
the title link should be just the title, with a URL for the page in
view_node.

If that's there and the data attribute isn't rendering, then
benefitSearch.js is cached or out of date. Do lInes 328 and 339 have the
data-analytics attribute in the link markup?

**Comment by IsabelLaurenceau** [comment]
Your image didn't upload correctly

**Comment by IsabelLaurenceau** [comment]
I flushed the css and js and same output: 
Screenshot 2024-07-29 at 9 23 09 AM

**Comment by omerida** [comment]
oh, hmm. I see the testing wasn't clear enough. That attribute is only
added to links in the search results down below the life event grid section
you're looking at.

**Comment by IsabelLaurenceau** [comment]
Oh okay got it. Yes they are there in the results section. Will approve and merge

**Review by IsabelLaurenceau — APPROVED** [review]

**Pull request merged**
