### PR TITLE
Usagov 1514 benefits search theming

### PR DESCRIPTION
**Pull request by lacorie-gsa**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-1628

## Description

- Added SVG icons for life event cards
- Updated benefits-search.css to uswds standards
- Updated templates to use fields for life events and benefits search

## Type of Changes

- [x] New Feature
- [ ] Bugfix
- [x] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
  - Note that this will look slightly different from the designs because the margin for the design is not the same as the actual site.
image

- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

## Testing Instructions

If there is life events content tagged already, you should just be able to view the benefits search page.

### Requires New Config
- [ ] Yes
- [x] No

### Requires New Content
- [ ] Yes
- [x] No

### Validation Steps
- Are life events showing with the appropriate icons.
- Benefits category show when checked
- Clear selections button works 
- Results show correctly
- Resizing to mobile works 

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders
- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions
Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

### CODE REVIEW

**Comment by IsabelLaurenceau** [comment]
I have one question. When I have results (like filter1.png) but press another feature the results are hidden again (filter2). Is this the expected functionality? If so I am able to approve and merge. 

Filter1:
filters

Filter2:
fliter2

icon

**Review by IsabelLaurenceau — COMMENTED** [review]
See comment above

**Comment by lacorie-gsa** [comment]
Hi @IsabelLaurenceau, Yes I believe this is the intended functionality for this to let the user know the data selection has been changed.

**Comment by akf** [comment]
> Hi @IsabelLaurenceau, Yes I believe this is the intended functionality for this to let the user know the data selection has been changed.

I can confirm. This is the way it's been working when Oscar demoed it (without these theme changes) and it seems to be what everyone expected to see. 

There will be another round of user testing, so maybe we will get direction later to automatically re-query with the new filter.

**Review by IsabelLaurenceau — APPROVED** [review]
Sounds good :) Approved!

**Pull request merged**
