### PR TITLE
Usagov 911 report a problem

### PR DESCRIPTION
**Pull request by IsabelLaurenceau**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-911

## Description

The report a problem form has multiple inputs that are deleted if content changes any of the text above it in the Drupal cms. This takes just the form and the js out of the cms and still allows content the ability to edit most of the page. 

### Testing
-Rebuild theme registry and flush cache to get the new twig and js files. 
-You will have to make a new basic page for Spanish and English and fill out three fields each. 
The URLS must match for the twig content to show on the page. 
localhost is not allowed for salesforce to send so we can't actually check that the form is working. I've tested with having the code in the cms it does work. We will test again once it's on dev. 
The main thing you are looking for is that there are no jquery or js errors. 

English- Report an issue with the website USA.gov
URL: /site-issue-report-form
CUSTOM TWIG CONTENT: Make sure it's selected
BODY:
```
<p>Although we link to other government websites, we can only update pages with USA.gov in their web address (URL).</p>

<p>Types of issues to share with us:</p>

<ul class="emailqstn">
	<li>Hyperlinks that are broken or go to the wrong place</li>
	<li>Out-of-date phone numbers, addresses, or agency program names</li>
	<li>Mistakes in our content</li>
	<li>Pages on our website that do not display properly</li>
	<li>Functionality on our website that is not working correctly</li>
</ul>

<p><strong>Please include the URL of the page with the problem.</strong> You can get the URL by going back to the page and then copying the URL from the address bar of your browser.</p>

<p>If necessary, we may need to contact you for more details about the problem. This is why the form requests your first name and email address. We will not use your contact information for any other purpose.</p>

<p>Thank you for helping us improve USA.gov.</p>

<drupal-paragraph data-embed-button="paragraphs" data-entity-label="USWDS Components" data-paragraph-id="3e5c2be0-4eda-4a02-aa8e-1ae501f8327e"></drupal-paragraph>
```

Spanish- Infórmenos sobre problemas en USAGov en Español
URL: /reporte-problemas-en-este-sitio-web
CUSTOM TWIG CONTENT: Make sure it's selected
BODY:
```
<p>Infórmenos sobre problemas con USA.gov en Español</p>

<p>Utilice este formulario para reportar problemas y errores al usar USA.gov en Español. Aunque nuestro sitio web incluye enlaces a otros sitios web del Gobierno, sólo podemos corregir nuestras páginas que contienen USA.gov en la  dirección (URL, sigla en inglés).</p>

<p> Tipo de problemas que puede reportar:</p>

<ul class="emailqstn">
<li>Enlaces rotos o que apuntan al lugar equivocado. </li>
<li>Números de teléfono, direcciones o nombres de programas de agencias que no están actualizados. </li>
<li>Errores en nuestro contenido.</li>
<li>Páginas en nuestro sitio web que no se ven correctamente.</li>
<li>Alguna funcionalidad que esté fallando en nuestro sitio web. </li>
<li>Por favor incluya el URL de la página con el problema. Puede obtener el URL volviendo a la página y luego copiándolo de la barra de direcciones. </li>
</ul>

<p>Si es necesario, es posible que nos comuniquemos con usted para obtener más detalles sobre el problema. Por esa razón le pedimos su nombre y dirección de correo electrónico en el formulario. No utilizaremos su información de contacto para ningún otro propósito. </p>


<p>Gracias por ayudarnos a mejorar USA.gov en Español.  </p>
```

## Checklist for the Developer

- [x] A link to the JIRA ticket has been added above.
- [x] The JIRA ticket identifies the desired result of this change.
- [x] The JIRA ticket contains clear acceptance criteria.
- [x] The JIRA ticket contains clear testing steps.
- [x] The JIRA ticket contains a description of "Done".
- [x] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Comment by cwacht** [comment]
I created the 2 pages, and it looks like the forms from the template files are showing up as expected. One change that I think should be made is on the spanish page, I see an input after the captcha labeled "Please ignore this box." I think it is meant to be inside of the visually hidden `<p>` tag.

In my browser console I see a few errors, but they all seem to be from the mutation observer that reports every time an attribute is modified, so I dont think they are related to this pull request.

2 other things of note:
- The spanish body content provided in this PR does not have the HTML tags, so my test page looks a bit bland, but I think that is inconsequential.
- The english body content includes a `<drupal-paragraph>` element, but I dont know how that embedded paragraph was configured so I could not test that piece of content.

**Comment by IsabelLaurenceau** [comment]
On it, thanks! I'll let you know when it's ready for a re-review.

**Comment by IsabelLaurenceau** [comment]
Alright moved the p tag that was closed to early in the Spanish twig template and included the html tags for the Spanish body! The Drupal paragraph isn't important for the testing, since it is just content.

**Review by cwacht — DISMISSED** [review]
Looks good!

**Comment by cwacht** [comment]
It looks like we will now be required to resolve lint errors before we can merge pull requests.

**Review by cwacht — APPROVED** [review]

**Pull request merged**
