### PR TITLE
USAGOV-597-Flag-card-styles: Remove border radius from all 4 corners

### PR DESCRIPTION
**Pull request by cwacht**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-597

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Review by IsabelLaurenceau — CHANGES_REQUESTED** [review]
I made sure to flush the cache but it's still showing the rounded corner on the right side of the image for me
Screen Shot 2022-12-05 at 10 27 00 AM

also this may be separate but the USWDS component icon wasn't showing for me in the WYSIWYG editor. I only found it because of the shading on hover 
Screen Shot 2022-12-05 at 10 25 29 AM

**Comment by IsabelLaurenceau** [comment]
Screen Shot 2022-12-05 at 10 42 22 AM

Also if it's helpful I went into the dev tools and it looks like the media query is overriding your changes

**Comment by akf** [comment]
> also this may be separate but the USWDS component icon wasn't showing for me in the WYSIWYG editor. I only found it because of the shading on hover

Just butting in to say that's a pre-existing issue. There's a ticket about it: USAGOV-527.

**Comment by cwacht** [comment]
Thanks for the feedback. It turns out that they had a higher specificity for when the card image is positioned to the right. I accounted for that now.

**Comment by IsabelLaurenceau** [comment]
Looks good!

**Review by IsabelLaurenceau — APPROVED** [review]

**Pull request merged**
