### PR TITLE
USAGOV-1814: add hover affect an styles for pagination

### PR DESCRIPTION
**Pull request by clmedders**
## Jira Task

[USAGOV-1814](https://cm-jira.usa.gov/browse/USAGOV-1814)

## Description
Updated styles for hover affect on pagination for the from on the benefits page.  Also applied updated styles such as border width and focus 

## Type of Changes

- [ ] New Feature
- [ ] Bugfix
- [x] Frontend (Twig, Sass, JS)
Screenshot 2024-08-09 at 11 01 31 AM
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

## Testing Instructions

1. start up local and cd into the Drupal theme and run `npm run build` to apply the new styles. 
2. scroll to the form and select several checkboxes and click `apply selections`
3. have [the beta site](https://beta-stage.usa.gov/find-benefits-category?t=58-35&pg=1) pulled up as well to help compare

### Change Requirements

- [ ] Requires New Documentation (Link: {})
- [ ] Requires New Config
- [ ] Requires New Content

### Validation Steps

- Validate that the new hover styles is applied
- Validate that the new border is present 
- Validate that focus styles is applied 
- Validate no major visual regressions

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
4. Find the commit of this pull request.
5. Build and deploy the changes.
6. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

### CODE REVIEW

**Comment by omerida** [comment]
@clmedders can you add the style to undelrine the prev/next links?

**Comment by YaritzaGarcia** [comment]
> @clmedders can you add the style to undelrine the prev/next links?

Hello! I just reviewed this PR and everything looks great. @clmedders Do you want me to wait for you to make the change that @omerida mentioned or do you want me to approve it now?

**Comment by clmedders** [comment]
@YaritzaGarcia i just talked with Oscar and got a better idea of whats need ill make the update and let you know when thats done!

**Comment by clmedders** [comment]
@YaritzaGarcia this is ready for review and merge when you are ready!

**Review by YaritzaGarcia — APPROVED** [review]

**Pull request merged**
