### PR TITLE
USAGOV-1909: Scope wizard breadcrumbs

### PR DESCRIPTION
**Pull request by DaleMHFrey**
Make wizard breadcrumbs work correctly across all root-level wizards

https://cm-jira.usa.gov/browse/USAGOV-1909

## Description
I changed the logic that renders breadcrumbs for wizard taxonomy-terms. Rather than using the menu system, this logic looks up the current taxonomy-term, finds its parents, and renders the breadcrumbs based on that.

## Type of Changes

- [ ] New Feature
- [ ] Bugfix
- [ ] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [x] Other

## Testing Instructions
Created a new root-level wizard (and maybe som children), go to that wizard on the front end, and confirm that the breadcrumbs reference that wizard [rather than something else].

### Change Requirements

- [ ] Requires New Documentation (Link: {})
- [ ] Requires New Config
- [ ] Requires New Content

### Validation Steps

- Test instruction 1
- Test instruction 2
- Test instruction 3

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

### CODE REVIEW

**Comment by clmedders** [comment]
@DaleMHFrey looks like there are some linting fails that need to be addressed

**Comment by DaleMHFrey** [comment]
> @DaleMHFrey looks like there are some linting fails that need to be addressed

Oops! Ok, this is now fixed 👍

**Review by mdranove — COMMENTED** [review]
This has a couple of problems, first of all the variable $crumb is not set, I think you meant $newCrumb, but even so switching it does not produce the desired results.

As it so happens, the requirements for this changed anyway, so I'm going to go ahead and tackle this one.

**Comment by DaleMHFrey** [comment]
I am closing this PR as Mike seems to have an alternative solution

**Pull request closed without merging**
