### PR TITLE
USAGOV-1903-orphaned-warnings:

### PR DESCRIPTION
**Pull request by omerida**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-1903

## Description

 When looking for orphaned entities, adds a check to ensure we only inspect reference fields that can point to the same entity type that we are deleting.

## Type of Changes

- [ ] New Feature
- [x] Bugfix
- [ ] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

## Testing Instructions

You can see the list of nodes referenced in the ticket with the USAgov production snapshot from Aug 20th before switching to this branch.

image

This PR fixes the list of nodes 

image

### Change Requirements

- [ ] Requires New Documentation (Link: {})
- [ ] Requires New Config
- [ ] Requires New Content

### Validation Steps

- Go delete https://localhost/node/37/delete, confirm only one item shows

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

### CODE REVIEW

**Review by akf — APPROVED** [review]
This works, and I still see warnings about a few things I thought to check (Federal directory synonyms, for one).

**Comment by omerida** [comment]
I checked other content types and didn't see warning but I  may not have looked at the right nodes. How can I reproduce the warnings?

The one side-effect I noticed (and led to the fix around lines 70) is that now other entities besides nodes show up in the list, like the taxonomy term line when deleting a life event.

image

**Comment by akf** [comment]
To be clear, the "warnings" in this case were good. Federal directory synonyms are an example: 

- Look for Content of type "Federal Directory Synonym"
- Open one; you'll see that it has a link to an "Agency Reference." Follow that link! 
- Select "Delete"
- You'll see something like this: 

Screenshot 2024-08-28 at 9 15 36 AM

(We don't publish the synonyms directly; they're just used in the A-Z index.)

Incidentally, I'm going to be adding a new ticket because code actually supports configuration to automatically delete entities or clear references and none of it's configured to do anything but "skip." But I'm uncertain whether there was a decision not to enable more because the functionality wasn't considered solid enough (and look, we just found a bug), or if, more likely, someone failed to check in a config file.

**Comment by omerida** [comment]
Phew, that matches with what I saw when I compared the warnings between dev
and my branch across some content types. That's how I found the life events
delete was throwing an exception because it was now getting taxonomy
entities.

**Pull request merged**
