### PR TITLE
USAGOV-1620: PXBF release v0.4.0.beta.1

### PR DESCRIPTION
**Pull request by scottqueen-bixal**
Benefit Finder v0.4.0.beta.1
https://github.com/GSA/px-benefit-finder/releases/tag/v0.4.0.beta.1

## Related Issues

https://github.com/GSA/px-benefit-finder/milestone/7?closed=1

## Type of Changes

- [ ] New Feature
- [x] Bugfix
- [x] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [x] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

### Data Analytics Improvements

[Data Layer Value stale on new view](https://github.com/GSA/px-benefit-finder/issues/1334)	https://github.com/GSA/px-benefit-finder/issues/1334
[Test Datalayer push event](https://github.com/GSA/px-benefit-finder/issues/1318)	https://github.com/GSA/px-benefit-finder/issues/1318

### a11y improvements

[Modal Buttons](https://github.com/GSA/px-benefit-finder/issues/1270)	https://github.com/GSA/px-benefit-finder/issues/1270
[Informational List on main page: adding alt-text on icons and removing alert components](https://github.com/GSA/px-benefit-finder/issues/1269)	https://github.com/GSA/px-benefit-finder/issues/1269
[Summary Component - Content Update](https://github.com/GSA/px-benefit-finder/issues/1235)	https://github.com/GSA/px-benefit-finder/issues/1235
[Error states on fields are failing contrast testing](https://github.com/GSA/px-benefit-finder/issues/1222)	https://github.com/GSA/px-benefit-finder/issues/1222
[Button outline styles on focus are not displaying as expected](https://github.com/GSA/px-benefit-finder/issues/1214)	https://github.com/GSA/px-benefit-finder/issues/1214

### Benefit Finder Module Improvements

[Replace type String "TRUE" with type Boolean `true`](https://github.com/GSA/px-benefit-finder/issues/1307)	https://github.com/GSA/px-benefit-finder/issues/1307
[Update automatic JSON data file generation message](https://github.com/GSA/px-benefit-finder/issues/1293)	https://github.com/GSA/px-benefit-finder/issues/1293

## Detailed Testing steps

>  Changes in this release require a rebuild of the JSON data

To manually generate JSON from our application:

- [ ] /benefit-finder/api/life-event/death/jsonfile
- [ ] /benefit-finder/api/life-event/retirement/jsonfile
- [ ] /benefit-finder/api/life-event/disability/jsonfile
- [ ] /benefit-finder/api/life-event/es_death/jsonfile
- [ ] /benefit-finder/api/life-event/es_retirement/jsonfile
- [ ] /benefit-finder/api/life-event/es_disability/jsonfile

### Data Analytics Improvements

[Data Layer Value stale on new view](https://github.com/GSA/px-benefit-finder/issues/1334)	https://github.com/GSA/px-benefit-finder/issues/1334
[Test Datalayer push event](https://github.com/GSA/px-benefit-finder/issues/1318)	https://github.com/GSA/px-benefit-finder/issues/1318

- [ ] visit `/benefit-finder/death`
- [ ] open inspector console
- [ ] run console.log(window.dataLayer)
- [ ] ensure, the following keys  and values are included in the `bf_page_change` event - pushed to the `dataLayer` array,

```
{
    "event": "bf_page_change",
    "bfData": {
        "pageView": "bf-intro",
        "viewTitle": "Benefit finder: death of a loved one"
    }
}
```

- [ ] continue to the first step of the form
- [ ] run console.log(window.dataLayer)
- [ ] ensure, the following keys and values are included in the `bf_page_change` event  - pushed to the `dataLayer` array,

```
{
    "event": "bf_page_change",
    "bfData": {
        "pageView": "bf-form",
        "viewTitle": "About the applicant"
    }
}
```

- [ ] complete the required form values on the first step
- [ ] continue to the second step of the form
- [ ] run console.log(window.dataLayer)
- [ ] ensure, the following keys and values are included in the `bf_page_change` event  - pushed to the `dataLayer` array,

```
{
    "event": "bf_page_change",
    "bfData": {
        "pageView": "bf-form",
        "viewTitle": "About the deceased"
    }
}
```

- [ ] complete the required form values on the second step
- [ ] continue to the next step of the form, this will trigger the modal
- [ ] while the modal is open, run console.log(window.dataLayer)
- [ ] ensure, the following keys and values are included in the `bf_modal_open` event  - pushed to the `dataLayer` array,

```
{
    "event": "bf_modal_open",
    "bfData": {
        "pageView": "bf-form",
        "viewTitle": "About the deceased",
        "modalOpen": true
    }
}
```

- [ ] click, review results
- [ ] run console.log(window.dataLayer)
- [ ] ensure, the following keys and values are included in the `bf_page_change` event  - pushed to the `dataLayer` array,

```
{
    "event": "bf_page_change",
    "bfData": {
        "pageView": "bf-verify-selections",
        "viewTitle": "Review and confirm"
    }
}
```

- [ ] click continue
- [ ] run console.log(window.dataLayer)
- [ ] ensure, the following keys and values are included in the `bf_page_change` event pushed to the `dataLayer` array,

```
{
    "event": "bf_page_change",
    "bfData": {
        "pageView": "bf-result-view",
        "viewTitle": "Your potential benefits",
        "viewState": "bf-eligible-view"
    }
}
```

- [ ] ensure, the following keys and values are included in the `bf_count` event pushed to the `dataLayer` array,
- [ ] note, values should match result counts
```
{
    "event": "bf_count",
    "bfData": {
        "eligible": NUM,
        "moreInfo": NUM,
        "notEligible": NUM
    }
}
```

- [ ] click, cta button "See benefits you did not qualify for" 
- [ ] run console.log(window.dataLayer)
- [ ] ensure, the following keys and values are included in the `bf_page_change` event pushed to the `dataLayer` array,

```
{
    "event": "bf_page_change",
    "bfData": {
        "pageView": "bf-result-view",
        "viewTitle": "Benefits you did not qualify for",
        "viewState": "bf-not-eligible-view"
    }
}
```

### a11y improvements

[Modal Buttons](https://github.com/GSA/px-benefit-finder/issues/1270)	https://github.com/GSA/px-benefit-finder/issues/1270

- [ ] navigate form filling out required fields
- [ ] click modal trigger button "continue"
- [ ] inspect DOM
- [ ] search for `bf-modal bf-usa-button-group`
- [ ] ensure that inside this group contains an `un-orderd` list of `buttons`

expected markup

Screenshot 2024-05-17 122718

[Informational List on main page: adding alt-text on icons and removing alert components](https://github.com/GSA/px-benefit-finder/issues/1269)	https://github.com/GSA/px-benefit-finder/issues/1269

- [ ] visit `/benefit-finder/death`
- [ ] inspect DOM, ensure that information icon in notices list has the following values;

1.  `en` locale === `aria-label="Important" role="img"`

expected:
Screenshot 2024-06-12 132717

2.  `es` locale === `aria-label="Importante" role="img"`

[Error states on fields are failing contrast testing](https://github.com/GSA/px-benefit-finder/issues/1222)	https://github.com/GSA/px-benefit-finder/issues/1222

- [ ] navigate to `/benefit-finder/death`
- [ ] navigate to first step of form
- [ ] click continue button to trigger error state
- [ ] tab through form to view focus state of elements, or
- [ ] open inspector in web console force "focus" state on all the elements that have errors
- [ ] ensure that there is a 2px separation between the focus and the red outline of the error state 

expected:
focus state input elements

[Button outline styles on focus are not displaying as expected](https://github.com/GSA/px-benefit-finder/issues/1214)	https://github.com/GSA/px-benefit-finder/issues/1214

- [ ] visit `/benefit-finder/death`
- [ ] navigate to the first step in form
- [ ] open inspector in web console force "focus" state on both buttons in the button group at the bottom of step 
- [ ] ensure that there is a white inner stroke against the focus outline

expected
Screenshot 2024-05-28 at 8 14 50 AM

### Content improvements

[Summary Component - Content Update](https://github.com/GSA/px-benefit-finder/issues/1235)	https://github.com/GSA/px-benefit-finder/issues/1235

- [ ] navigate to results view of form
- [ ] ensure summary component has the following content updates

expected changes

`en` locale
Screenshot 2024-05-30 at 4 13 25 PM

- [ ] toggle spanish
- [ ] navigate to results view of form
- [ ] ensure summary component has the following content updates

expected changes

`es` locale
Screenshot 2024-05-30 at 4 15 19 PM

### Custom Module Improvements

[Update automatic JSON data file generation message](https://github.com/GSA/px-benefit-finder/issues/1293)	https://github.com/GSA/px-benefit-finder/issues/1293

- [ ] Navigate to `/admin/content?combine=&type=bears_life_event_form&status=All&langcode=All`
- [ ] Go to life event form "Benefit finder: death of a loved one" edit page
- [ ] Edit and save as draft
- [ ] Verify that it lists the progress bar with title "Generating draft JSON data files"

- [ ] Edit the content again and save as published
- [ ] Verify that it shows the progress bar with title "Generating both draft and published JSON data files"

[Replace type String "TRUE" with type Boolean `true`](https://github.com/GSA/px-benefit-finder/issues/1307)	https://github.com/GSA/px-benefit-finder/issues/1307

Testing the JSON Response

- [ ] Navigate to `/benefit-finder/api/life-event/death`
- [ ] open network tab in request
- [ ] view `death.json`
- [ ] Verify that "required", "hasChild", and "SourceIsEnglish" have boolean value
- [ ] Verify that `"required": true,`
- [ ] Verify that "`hasChild": true,`
- [ ] Verify that "`SourceIsEnglish": true,`

Testing the Application

- [ ] navigate to `/benefit-finder/death`
- [ ] navigate to first step of form
- [ ] Verify that  when `"required": true,` is in the fieldset object, a `required` flag is associated with the fieldset label
- [ ] Click `continue` without filling out any field values
- [ ] Verify that any field marked with required is flagged with an error state
- [ ] complete required fields
- [ ] navigate to next step by clicking `continue`
- [ ] Verify that  when "`hasChild": true,` is in the fieldset object, the related child fieldset is hidden. `"Did the deceased actively serve in the U.S. military?"`
- [ ] Verify that  when "`hasChild": true,` is in the fieldset object, the related child fieldset is visible when the dependency  option value is valid, `["Yes"]`
- [ ] Verify that  when "`SourceIsEnglish": true,` the source link in a benefit indicates `(en inglés)`
- [ ] toggle ES locale, navigate through form and find `Visite Departamento de Defensa (DOD) (en inglés)` in the benefits

### Requires New Config
- [x] Yes (regenerate all of JSON Data Files)
- [ ] No

To manually generate JSON from our application:

- [ ] /benefit-finder/api/life-event/death/jsonfile
- [ ] /benefit-finder/api/life-event/retirement/jsonfile
- [ ] /benefit-finder/api/life-event/disability/jsonfile
- [ ] /benefit-finder/api/life-event/es_death/jsonfile
- [ ] /benefit-finder/api/life-event/es_retirement/jsonfile
- [ ] /benefit-finder/api/life-event/es_disability/jsonfile

### Requires New Content
- [x] Yes
- [ ] No

### Validation Steps
- Test instruction 1
- Test instruction 2
- Test instruction 3

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders
- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions
Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

### CODE REVIEW

**Review by gchi25 — APPROVED** [review]
Tested. Worked as expected.

**Review by akf — APPROVED** [review]
I saw one thing that is not exactly as described in the review instructions: the `bf_page_change` event is duplicated in window.dataLayer for the first page. For example: 

```
    {
        "event": "bf_page_change",
        "bfData": {
            "pageView": "bf-intro",
            "viewTitle": "Buscador de beneficios: muerte de un ser querido"
        },
        "gtm.uniqueEventId": 5
    },
    {
        "event": "bf_page_change",
        "bfData": {
            "pageView": "bf-intro",
            "viewTitle": "Buscador de beneficios: muerte de un ser querido"
        },
        "gtm.uniqueEventId": 6
    },
```

This is true for "death" as well as "muerte" and I imagine all the others. I don't know whether that matters (probably), nor whether it's worth holding up this release for (probably not?). For my part, I'm approving this but not merging it because this is a Draft PR. If you change it to not-a-draft, I will merge ... or someone else can, no need to wait on me!

**Comment by scottqueen-bixal** [comment]
> I saw one thing that is not exactly as described in the review instructions: the `bf_page_change` event is duplicated in window.dataLayer for the first page. For example:
> 
> ```
>     {
>         "event": "bf_page_change",
>         "bfData": {
>             "pageView": "bf-intro",
>             "viewTitle": "Buscador de beneficios: muerte de un ser querido"
>         },
>         "gtm.uniqueEventId": 5
>     },
>     {
>         "event": "bf_page_change",
>         "bfData": {
>             "pageView": "bf-intro",
>             "viewTitle": "Buscador de beneficios: muerte de un ser querido"
>         },
>         "gtm.uniqueEventId": 6
>     },
> ```
> 
> This is true for "death" as well as "muerte" and I imagine all the others. I don't know whether that matters (probably), nor whether it's worth holding up this release for (probably not?). For my part, I'm approving this but not merging it because this is a Draft PR. If you change it to not-a-draft, I will merge ... or someone else can, no need to wait on me!

This is expected @akf, but you are right, was not in the test instructions. it is related to reacts render cycle and cache establishment. We've been told by our data analyst that this is ok for his collection.

**Comment by scottqueen-bixal** [comment]
updated branch and moved to `ready for review`

**Comment by gchi25** [comment]
Tested in cms-dev.usa.gov
Worked as expected.

**Pull request merged**
