### PR TITLE
Usagov 1740 benefits category ux

### PR DESCRIPTION
**Pull request by omerida**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-1740

## Description

Color, margin, hover state updates from UX review

## Type of Changes

- [ ] New Feature
- [ ] Bugfix
- [x] Frontend (Twig, Sass, JS)
image

image

- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

## Testing Instructions

Need benefits search pages set up

### Change Requirements

- [ ] Requires New Documentation (Link: {})
- [ ] Requires New Config
- [ ] Requires New Content

### Validation Steps

- Confirm checkbox focus state is teal
- Confirm category brackground is #E7F6F8
- Confirm padding between buttons is 24px on desktop
- Confirm padding above "Find benefits by category" title is 28px on mobile
- Confirm button hover states match figma handoff

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

### CODE REVIEW

**Review by IsabelLaurenceau — CHANGES_REQUESTED** [review]
Screenshot 2024-07-22 at 3 15 52 PM
It looks like the the padding on the “Find benefits by category” title is still 48px but everything else is right!

**Comment by omerida** [comment]
> It looks like the the padding on the “Find benefits by category” title is still 48px but everything else is right!

That one's confusing. The padding above that title varies between mobile and deskop. Mobile should be 24px and desktop 44px on the [Figma designs](https://www.figma.com/design/r3HT62yMfOjx5yInksCBH4/Benefit.gov-transition-design---HANDOFF?node-id=10003-1711&t=iHAgVKSf9ZMpHuFr-0)

**Comment by IsabelLaurenceau** [comment]
Ah got it. Okay just looks like now there's a merge conflict but if you resolve that I can retest and approve

**Comment by omerida** [comment]
Should be resolved now

**Review by IsabelLaurenceau — APPROVED** [review]

**Pull request merged**
