### PR TITLE
USAGOV-815-watchdog-stdout: adding log stdout module

### PR DESCRIPTION
**Pull request by jacobaaronyeager**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-815

## Description

Uninstall dblog / install stdout_log

**Pre Deployment:**
I believe we should perform the following steps in the target env, prior to deployment:

1. Disable DBLog module
2. Delete the Database Log View (views.view.dblog)

I encountered some errors regarding views.view.dblog requiring a module that would no longer be present after config import, when trying to run locally with an existing database.

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Review by akf — DISMISSED** [review]
Please commit the changes to composer.lock as well.

**Comment by akf** [comment]
In addition to updating the composer.lock, you'll need to export and commit the configuration for: 
  * enabling the module 
  * turning on logging to stdout (looks like it's automatic on enabling, but creates a settings file) 
  * disabling dblog. Otherwise the messages still go to the database.
I deleted composer.lock and installed this thing, and now that I've turned it on I'm getting full stack traces in STDOUT for every warning (I introduced a bug for this purpose). Only the first line says [WARNING] -- and we can edit that template, but it doesn't look like we can trim out the stack trace. (I think this is probably fine. Just a thing to be aware of.)

**Comment by jacobaaronyeager** [comment]
@akf Updated.  Let me know!

**Review by ghost — DISMISSED** [review]

**Review by akf — COMMENTED** [review]
I'm attempting to clear my "request changes" review.

**Review by ghost — APPROVED** [review]
I think this is good to go, and we should just test the pre-deploy steps before we merge to dev.

**Pull request merged**
