### PR TITLE
USAGOV-904-50-state-go-button

### PR DESCRIPTION
**Pull request by cwacht**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-904

## Description

Make the Go button full-width on mobile

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Comment by IsabelLaurenceau** [comment]
The button is full width however it is not left aligned with the dropdown like in the mockup on Jira. Attaching my screen shots from Safari and Firefox as reference

Screen Shot 2023-05-11 at 8 55 21 AM

Screen Shot 2023-05-11 at 8 55 02 AM

**Review by IsabelLaurenceau — CHANGES_REQUESTED** [review]
See above comment with photo

**Comment by cwacht** [comment]
Thanks! It looks like that issue was caused by the button style using a breakpoint of max-width:30em while the USWDS responsive breakpoints use min-width:30em, so for a screen width of exactly 30em (480px) it would show our mobile style for the button and the non-mobile style for other things. I changed the button style to use min-width to resolve this.

**Comment by IsabelLaurenceau** [comment]
I ran "bin/npm run build" and flushed my cache but I'm still not getting them aligned
Screen Shot 2023-05-15 at 8 04 32 AM
Screen Shot 2023-05-15 at 8 05 43 AM

**Review by IsabelLaurenceau — CHANGES_REQUESTED** [review]
I ran "bin/npm run build" and flushed my cache but I'm still not getting them left-aligned 
Screen Shot 2023-05-15 at 8 04 32 AM
Screen Shot 2023-05-15 at 8 05 43 AM

**Comment by cwacht** [comment]
I cannot pinpoint any reason why we are seeing different things. Perhaps we can figure it out with a screenshare session when you have time to meet.

**Comment by cwacht** [comment]
I've made the changes in the 50-state template and deleted the old template. I also changed a little bit of the javascript but I believe it will function exactly the same as before.

**Comment by IsabelLaurenceau** [comment]
Functionality is indeed all still there and the button is now centered. I just want to check before I approve that it's okay the button and drop down aren't aligned on the left and right? I think it looks good but I see it's different from the Jira ticket. 
Screen Shot 2023-05-16 at 4 48 53 PM
Screen Shot 2023-05-16 at 4 47 16 PM

**Comment by cwacht** [comment]
Yes, the USWDS has styles that add padding around the full width buttons but not other form elements, and I didn't want to mess with those styles unless someone says that we really want the button and dropdown widths to match.

**Comment by IsabelLaurenceau** [comment]
Perfect approving!

**Review by IsabelLaurenceau — APPROVED** [review]

**Pull request merged**
