### PR TITLE
USAGOV-973: Automatically delete bad es/index.html and retry tome

### PR DESCRIPTION
**Pull request by akf**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-973

## Description

Modified the tome-sync.sh and tome-run.sh scripts: 
* tome-sync.sh: Now checks for the phrase "About us" on the Spanish home page, in addition to a "too small" page, as reasons not to push to S3
* tome-sync.sh: If either of the above is detected, removes the es/index.html page (so it will be updated on the next run) and touches /tmp/tome-log/retry-on-next-run
* tome-run.sh: checks for /tmp/tome-log/retry-on-next-run and, if present, deletes it and proceeds as if content had been updated. 

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Still looking at this, but atm I see that the missing file case will still invoke the small file case, so you get both warning messages in the case if a missing file.

**Comment by akf** [comment]
Thanks! I forgot I did that. I became concerned that tome-sync might push files to S3 after I deleted es/index.html (or after a previous run did), so I decided to explicitly check for that and wrap it into the "too small" case.

**Comment by ghost** [comment]
Here is my horrible test script.  I pulled the code out of context, as I don't think I can make tome reliably create the conditions to test all cases

EDIT:   I modified some of the if statements to achieve the desired results

```shell
#!/bin/sh
TOME_PUSH_NEW_CONTENT=1
RETRY_SEMAPHORE_FILE=/tmp/retry-on-next-run
ES_HOME_HTML_FILE=/tmp/index.html
ES_HOME_HTML_FILE_SMALL=/tmp/small-index.html
ES_HOME_HTML_FILE_NORMAL=/tmp/normal-index.html
ES_HOME_HTML_FILE_ENGLISH=/tmp/english-index.html

do_the_test () {

	export RETRY_SEMAPHORE_EXISTS=0
	if [ -f $RETRY_SEMAPHORE_FILE ]; then
	  export RETRY_SEMAPHORE_EXISTS=1
	  rm -f $RETRY_SEMAPHORE_FILE
	fi

	if [ "$RETRY_SEMAPHORE_EXISTS" != "0" ] ; then
	  echo
	  echo "Retry Semaphore file existed at startup."
	  echo
	fi

	ES_HOME_HTML_BAD=0
	if [ -f $ES_HOME_HTML_FILE ]; then
	  ES_HOME_HTML_SIZE=$(stat -c%s "$ES_HOME_HTML_FILE")
	else
	  ES_HOME_HTML_SIZE=0
	  ES_HOME_HTML_BAD=1
	  echo "WARNING: *** ES index.html does not exist ***"
	fi

	# Too-small file is probably a redirect page
	if [ $ES_HOME_HTML_BAD != "1" ] && [ $ES_HOME_HTML_SIZE -lt 1000 ]; then
	  echo "WARNING: *** ES index.html is way too small ($ES_HOME_HTML_SIZE bytes) ***"
	  ES_HOME_HTML_BAD=1
	fi

	if [ "$ES_HOME_HTML_BAD" != "1" ]; then
		# Sometimes Tome generates an English mobile menu on the Spanish home page
		ES_HOME_CONTAINS_ENGLISH_MENU=$(grep -c 'About us' $ES_HOME_HTML_FILE)
		if [ "$ES_HOME_CONTAINS_ENGLISH_MENU" != "0"  ]; then
	  		echo "WARNING: *** ES index.html appears to contain English nav ***"
	  		ES_HOME_HTML_BAD=1
		fi
	fi

	if [ "$ES_HOME_HTML_BAD" == "1" ]; then
	  # Delete the known-bad file; it may be re-created correctly on the next run.
	  rm -f $ES_HOME_HTML_FILE
	  touch $RETRY_SEMAPHORE_FILE
	  echo "Creating a retry semaphore file"
	  TOME_PUSH_NEW_CONTENT=0
	else
	  TOME_PUSH_NEW_CONTENT=1
	fi

    echo ES_HOME_HTML_BAD: $ES_HOME_HTML_BAD
	echo TOME_PUSH_NEW_CONTENT: $TOME_PUSH_NEW_CONTENT
}


cat <<STEXT > $ES_HOME_HTML_FILE_SMALL
too small to be a real html file
STEXT

cat <<NTEXT > $ES_HOME_HTML_FILE_NORMAL
HereDoc uses the ‘–‘ symbol to suppress any tab space from each line of heredoc text. In the following example, tab space is added at the start of each line, and the ‘–‘ symbol is used before the starting delimiter. When the script executes, all tab spaces are omitted from the starting of each line, but it creates no effect on normal space. Create a bash file named heredoc2.bash with the following script to test the function of ‘–‘.
HereDoc uses the ‘–‘ symbol to suppress any tab space from each line of heredoc text. In the following example, tab space is added at the start of each line, and the ‘–‘ symbol is used before the starting delimiter. When the script executes, all tab spaces are omitted from the starting of each line, but it creates no effect on normal space. Create a bash file named heredoc2.bash with the following script to test the function of ‘–‘.
HereDoc uses the ‘–‘ symbol to suppress any tab space from each line of heredoc text. In the following example, tab space is added at the start of each line, and the ‘–‘ symbol is used before the starting delimiter. When the script executes, all tab spaces are omitted from the starting of each line, but it creates no effect on normal space. Create a bash file named heredoc2.bash with the following script to test the function of ‘–‘.
HereDoc uses the ‘–‘ symbol to suppress any tab space from each line of heredoc text. In the following example, tab space is added at the start of each line, and the ‘–‘ symbol is used before the starting delimiter. When the script executes, all tab spaces are omitted from the starting of each line, but it creates no effect on normal space. Create a bash file named heredoc2.bash with the following script to test the function of ‘–‘.
NTEXT

cat <<ETEXT > $ES_HOME_HTML_FILE_ENGLISH
About us the ‘–‘ symbol to suppress any tab space from each line of heredoc text. In the following example, tab space is added at the start of each line, and the ‘–‘ symbol is used before the starting delimiter. When the script executes, all tab spaces are omitted from the starting of each line, but it creates no effect on normal space. Create a bash file named heredoc2.bash with the following script to test the function of ‘–‘.
HereDoc uses the ‘–‘ symbol to suppress any tab space from each line of heredoc text. In the following example, tab space is added at the start of each line, and the ‘–‘ symbol is used before the starting delimiter. When the script executes, all tab spaces are omitted from the starting of each line, but it creates no effect on normal space. Create a bash file named heredoc2.bash with the following script to test the function of ‘–‘.
HereDoc uses the ‘–‘ symbol to suppress any tab space from each line of heredoc text. In the following example, tab space is added at the start of each line, and the ‘–‘ symbol is used before the starting delimiter. When the script executes, all tab spaces are omitted from the starting of each line, but it creates no effect on normal space. Create a bash file named heredoc2.bash with the following script to test the function of ‘–‘.
HereDoc uses the ‘–‘ symbol to suppress any tab space from each line of heredoc text. In the following example, tab space is added at the start of each line, and the ‘–‘ symbol is used before the starting delimiter. When the script executes, all tab spaces are omitted from the starting of each line, but it creates no effect on normal space. Create a bash file named heredoc2.bash with the following script to test the function of ‘–‘.
ETEXT

#ls -l $ES_HOME_HTML_FILE_SMALL
#ls -l $ES_HOME_HTML_FILE_ENGLISH
#ls -l $ES_HOME_HTML_FILE_NORMAL

echo "#1. Try html file not exist"
	rm -f $ES_HOME_HTML_FILE
	do_the_test
	echo
	echo
	echo

echo "#2. Try html file too small"
	rm -f $ES_HOME_HTML_FILE
	cp $ES_HOME_HTML_FILE_SMALL $ES_HOME_HTML_FILE
	do_the_test
	echo
	echo
	echo

echo "# 3. Try html file english"
	rm -f $ES_HOME_HTML_FILE
	cp $ES_HOME_HTML_FILE_ENGLISH $ES_HOME_HTML_FILE
	do_the_test
	echo
	echo
	echo

echo "# 4. Try html file normal"
	rm -f $ES_HOME_HTML_FILE
	cp $ES_HOME_HTML_FILE_NORMAL $ES_HOME_HTML_FILE
	do_the_test
	echo
	echo
	echo

rm -f $ES_HOME_HTML_FILE
rm -f $ES_HOME_HTML_FILE_ENGLISH
rm -f $ES_HOME_HTML_FILE_NORMAL
rm -f $ES_HOME_HTML_FILE_SMALL
rm -f $RETRY_SEMAPHORE_FILE
```

**Comment by akf** [comment]
I decided to add those tests to the repo for posterity. There's enough to that, that someone might crib from it to make more formal tests someday.

**Comment by akf** [comment]
Re-reading your earlier comment ... We don't get two messages in the "missing file" case, we get this message: 

WARNING: *** ES index.html is way too small (0 bytes) ***

I maintain that this is close enough, even though it implies the existence of an empty file rather than the complete lack of a file.

**Review by ghost — APPROVED** [review]

**Pull request merged**
