### PR TITLE
USAGOV-645-footer-404: switch default from Spanish to English

### PR DESCRIPTION
**Pull request by IsabelLaurenceau**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-645

## Description

Switched the default footer text to be English instead of Spanish. 
On localhost/user and 404 pages the footer used to be in Spanish since the language wasn't set. 
Also adds back a div  with class="additional_body_info" for spacing between content and information. 

## Testing
Log in and clear the cache. 
Log back out. 
Navigate to localhost/user and verify footer is in English. 
Click on various pages and verify footer is in correct language. 

## Checklist for the Developer

- [x] A link to the JIRA ticket has been added above.
- [x] The JIRA ticket identifies the desired result of this change.
- [x] The JIRA ticket contains clear acceptance criteria.
- [x] The JIRA ticket contains clear testing steps.
- [x] The JIRA ticket contains a description of "Done".
- [x] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [x] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [x] Code Standards are followed, there are no bad practices in use.
- [x] Config changes (if any) include only necessary changes.
- [x] No errors in Drupal or Client Browser.
- [x] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Comment by ghost** [comment]
@IsabelLaurenceau tested with the following results:

OK - http://localhost/elected-officials
OK - http://localhost/es/funcionarios-electos

404 - http://localhost/testme
404 - but english footer - http://localhost/es/testme

OK - http://localhost/user/login
OK - but english footer - http://localhost/es/user/login

**Comment by IsabelLaurenceau** [comment]
@msvgsa So it looks like the 404 pages are not configured for locals. Since the pages aren't configured there isn't a language and it's defaulting to English. 
I think it's okay that the Spanish 404 gave us the English footer because on dev, stage and prod those pages are configured and will have the language set.
Alternatively, if you think it's better, I can write it so we use the pathname to determine the language. This just may need to be updated if we change how we do paths (which I think is a ticket already in JIRA for later).

**Comment by ghost** [comment]
> @msvgsa So it looks like the 404 pages are not configured for locals. Since the pages aren't configured there isn't a language and it's defaulting to English. I think it's okay that the Spanish 404 gave us the English footer because on dev, stage and prod those pages are configured and will have the language set. Alternatively, if you think it's better, I can write it so we use the pathname to determine the language. This just may need to be updated if we change how we do paths (which I think is a ticket already in JIRA for later).

Hi @IsabelLaurenceau - I think if everything is already set via config in the deployed environments, it is not that important to make further changes that are purely for local (IMO, anyway).

**Review by ghost — APPROVED** [review]
Changes reviewed and discussed w/ @IsabelLaurenceau

**Pull request merged**
