### PR TITLE
Usagov-126-meta-rel-link-tags-and-favicon-images

### PR DESCRIPTION
**Pull request by developer43**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-126

## Checklist for the Developer

- [x] A link to the JIRA ticket has been added above.
- [x] The JIRA ticket identifies the desired result of this change.
- [x] The JIRA ticket contains clear acceptance criteria.
- [x] The JIRA ticket contains clear testing steps.
- [x] The JIRA ticket contains a description of "Done".
- [x] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [x] The branch name of this PR matches the project standards.
- [x] QA steps are followed and any changes to process are updated in the ticket.
- [x] Code Standards are followed, there are no bad practices in use.
- [x] Config changes (if any) include only necessary changes.
- [x] No errors in Drupal or Client Browser.
- [x] Code has been tested locally (if possible).
- [x] Following AC and Testing Steps verify changes work as expected.
- [x] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Review by ednark — CHANGES_REQUESTED** [review]
If there is any other possible way to do this we should. There should never be a situation where we have to hardcode Node IDs into the templates. That is guaranteed to break.

**Comment by oadekoya12** [comment]
Make a function that will pass the required variables for the developer to complete the ticket.

**Review by ednark — DISMISSED** [review]

**Comment by oadekoya12** [comment]
@developer43 
I will clean out all the changes. Can you remove the ID, and we will create a new branch for the new ticket. Then we can approve this one after.

**Comment by oadekoya12** [comment]
@ednark 
I will approve this because all the IDs removed.
A new branch will be created for the new ticket.

**Review by oadekoya12 — APPROVED** [review]
Reviewed with Bryant.

1. All dpm removed
2. Node ID removed
3. Variable calls valid

**Pull request merged**
