### PR TITLE
USAGOV-1116-Phone-Numbers: Update telephoneForMobileNode.js

### PR DESCRIPTION
**Pull request by IsabelLaurenceau**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-1116

## Description

Phone numbers on agency index were missing on desktop (/agency-index).  Please check that phones numbers are now visible on **all** browsers. Please also check that phone numbers are visible on agency pages (/agencies/u-s-access-board) and state pages (states/alabama). 

## Checklist for the Developer

- [x] A link to the JIRA ticket has been added above.
- [x] The JIRA ticket identifies the desired result of this change.
- [x] The JIRA ticket contains clear acceptance criteria.
- [x] The JIRA ticket contains clear testing steps.
- [x] The JIRA ticket contains a description of "Done".
- [x] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Comment by cwacht** [comment]
With this change there is something odd happening on mobile where the phone number link exists twice. The first one has a clean tel link but no content. The second one has the dashes in the link and has the content. I have stepped through the script debugger, and it is not clear to me why this is happening.
Screenshot 2023-08-29 at 11 39 50 AM

**Comment by IsabelLaurenceau** [comment]
Hmm interesting okay let me look into this.

**Comment by cwacht** [comment]
It seems like things work properly when telephoneForMobileNode.js runs. Then, phoneForMobileinBody.js runs and splits the phone link into 2 links.

**Comment by IsabelLaurenceau** [comment]
Interesting. Yeah I see it's only happening on mobile. What's strange is that it's also happening in safari and phoneForMobileinBody shouldn't run in that browser.

**Comment by IsabelLaurenceau** [comment]
Oh I see this is happening on prod too!

**Comment by cwacht** [comment]
Changing the order of the scripts in usagov.libraries.yml so phoneForMobileinBody.js runs before telephoneForMobileNode.js seems to help.

**Comment by IsabelLaurenceau** [comment]
I think that last suggestion fixed it

**Comment by cwacht** [comment]
This is looking good for phone numbers in the directory records. There is something still happening to the /phone link in the footer (only in ~~Chrome~~ mobile). I think phoneForMobileinBody.js is turning part of the link to /phone into a tel link.

If this is a quick fix, we could solve it here. Otherwise, I can approve this PR and make a new ticket for the footer /phone link.

Edit: the footer phone number issue does not happen on pages that have other phone numbers in the content. So you wont see it if you're looking at a directory record page.

Edit again: It happens in all browsers (only in mobile screensizes). I initially only noticed it in chrome because I hadn't opened tabs to affected pages in the other browsers.

**Comment by IsabelLaurenceau** [comment]
Interesting that it doesn't happen on pages with phone numbers in the content. I think because this is high priority, we should approve this so it's able to be tested on dev tomorrow before Stage deploy Thursday. Since the link in the footer still works we can make a new ticket for the footer to be done later.

**Review by cwacht — APPROVED** [review]

**Comment by cwacht** [comment]
Circle CI is being slow I will keep checking for this merge in the pipeline.

**Comment by IsabelLaurenceau** [comment]
Made the new ticket on https://cm-jira.usa.gov/browse/USAGOV-1119

**Pull request merged**
