### PR TITLE
USAGOV-1458: Pxbf release v0.2.0.beta.1

### PR DESCRIPTION
**Pull request by scottqueen-bixal**
## Request integration to Dev by 
03/26/2024

Given that there is new config, the sooner the better.

### Requires New Content
- [x] Yes
- [ ] No

visit these paths after code is merged to generate new content from Benefit Finder App, generates new JSON data files
```
/benefit-finder/api/life-event/death/jsonfile
/benefit-finder/api/life-event/retirement/jsonfile
/benefit-finder/api/life-event/disability/jsonfile
/benefit-finder/api/life-event/es_death/jsonfile
/benefit-finder/api/life-event/es_retirement/jsonfile
/benefit-finder/api/life-event/es_disability/jsonfile
```

## Related Github Issue(s)
Milestone: [v0.2.0.beta.1](https://github.com/GSA/px-benefit-finder/milestone/1)

## Description

Latest build for integration from Benefit Finder Release
https://github.com/GSA/px-benefit-finder/releases/tag/v0.2.0.beta.1

## Type of Changes

- [x] New Feature
- [x] Bugfix
- [x] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [x] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

## Testing Instructions

- [x] Review Code
- [x] Ensure Tests are passing
- [ ] confirm functionality from the following issues

### a11y Improvements

1. https://github.com/GSA/px-benefit-finder/issues/1058

- [x] navigate to results view
- [x] view heading structure using ANDI
- [x] ensure heading levels increment `1-2-3-n`

2. https://github.com/GSA/px-benefit-finder/issues/956

- [x] turn on voice over
- [x] navigate through first step without entry
- [x] click continue 
- [x] note the error takes focus but does not announce to voice over

3. https://github.com/GSA/px-benefit-finder/issues/933

- [x] turn voice over on
- [x] navigate to first step, step nav
- [ ] note if two items are listed as "not-complete"
- [ ] compete required fields
- [ ] navigate to second step, step nav
- [ ] note if two items are listed, first as "completed", second as "not completed"
- [ ] navigate back to the first step
- [ ] navigate to the first step, step nav
- [ ] note if two items are listed, first as "completed", second as "not completed"

Expected:
https://github.com/GSA/px-benefit-finder/assets/37077057/181098c1-5c14-446e-be47-c9080f4258e6

### Design Improvements

1. https://github.com/GSA/px-benefit-finder/issues/908

- [x] navigate to end of form
- [x] view share and email buttons

Expected:
Screenshot 2024-02-27 at 2 10 40 PM

2. https://github.com/GSA/px-benefit-finder/issues/751

- [x] navigate to results page
- [x] validate that icons are appearing in relevant benefits cards

Expected:
Screenshot 2024-02-23 143511

3. https://github.com/GSA/px-benefit-finder/issues/710

- [x] complete form
- [x] open benefit accordion
- [x] note green checkmark icon is now included with eligible items

Expected:
Screenshot 2024-02-12 at 11 57 04 AM

### Content Improvements

1. https://github.com/GSA/px-benefit-finder/issues/819

- [ ] Navigate the application and confirm the following changes appear both in code and UI

| Before | After  | Where |
|-------------|--------------------|--------------------|
| Review Results  | Review results  | Intro page steps |
| Required | required | Adjacent to required fields |
| Review and Confirm | Review and confirm | Verify selections view  heading|
| Likely Eligible | Likely eligible | Items marked in results |
| More Information Needed | More information needed | items marked in results | 
| Not Eligible | Not eligible | Items marked in results |
| Error status | Error | Error message |
| All fields marked required must be completed | Complete all required fields | Error message |
| Complete Questions | Answer these questions | Section headings |
| Final Questions | Questions continued | Section headings |
| Time to complete [2-5 mins] | Estimated time [2-5 mins] | Time indicator, intro page |
| <ul><li>Your information **is not** shared, saved, or submitted. </li><li>Provide complete info to get more relevant results.</li><li>**This form is not an application.** You will need to apply for benefits with each agency.</li></ul> | <ul><li>**This is not an application.** This tool will help you find possible benefits.</li><li>Your answers **are not** saved or submitted.</li><li>**Answer all questions** to get better results.</li></ul> | Before you start bullets, intro page |
| No input given| Not answered | Review your results section |
| Date should follow the format 01 - January 22 1977 | Date should follow the format January 19 2000 | Date error message |

**Spanish**
| Before | After  | Where |
|-------------|--------------------|--------------------|
| Tiempo para completar | Tiempo estimado | Start page |
| <ul><li>Su información **no será** compartida, guardada o presentada.</li><li>Ingrese la información completa para obtener resultados más relevantes.</li><li>**Este formulario no es una aplicación.** Tiene que presentar una solicitud por cada beneficio.</li></ul> | <ul><li>**Esto no es una aplicación.** Este formulario le ayuda a encontrar beneficios.</li><li>Sus respuestas **no serán** guardadas o presentadas.</li><li>Para mejores resultados **responda todas las preguntas**.</li></ul> | Before you start bullets |
| Se requiere | requerido | Required fields |
| Estado de error | Error | Error message
| Todos los campos marcados como obligatorios deben ser completados. | Responda los campos requeridos. | Error message |
| No se ha dado ninguna entrada | No respondió | Review results section |
| Podría calificar para estos beneficios: | Podría ser elegible para estos beneficios: | Results sections | 
| Preguntas completas | Responda las preguntas | Page 1 section heading |
| Preguntas Continuación | Preguntas continuadas | Page 2 section heading | 
| La fecha debe seguir el formato 01 - 22 de enero de 1977. | Use el formato enero 19 2000 | Wrong date error message | 

### App Improvements

1. https://github.com/GSA/px-benefit-finder/issues/50

- [ ] navigate to results
- [ ] ensure that the source linked in the benefit displays `(en ingles)`
- [ ] navigate to the benefits you did not qualify for
- [ ] ensure that the source linked in the benefit displays that do not have `(en ingles)` link to spanish content sites
- [ ]  ensure that the source linked in the benefit displays that do have `(en ingles)` link to english content sites
- [ ] navigate to english version and ensure that no benefits indicate `(en ingles)`

*** if a site should be noted as english, but is not - review the content returned from the fetch, if that benefit has the correct boolean value in `SourceIsEnglish` key then content needs to be updated and will be done in CMS

2. https://github.com/GSA/px-benefit-finder/issues/888

class overrides, are `usa-` classes prefixed with `bf-`

```css
.bf-usa-<class> .usa-<class>
```

### Module Improvements

1. https://github.com/GSA/px-benefit-finder/issues/849

http://localhost/admin/content?combine=COVID&type=bears_benefit&status=All&langcode=en
- [ ] Go to benefit "COVID-19 funeral assistance" edit page.

- [ ] Test 1: Test acceptable values field empty
- [ ] Make acceptable values field empty.
- [ ] Click "Save".

image

You get error notifications and cannot save.

image

- [x] Test 2: Test acceptable value is not an option value of criteria
Input acceptable value "Unsure".

image

You get error notifications and cannot save.

image

2. https://github.com/GSA/px-benefit-finder/issues/924

- [ ] Go to `/benefit-finder/api/life-event/death`

- [ ] Check that the JSON data includes life event id in relative benefit object.

image

3. https://github.com/GSA/px-benefit-finder/issues/910

http://localhost/admin/content?combine=COVID&type=bears_benefit&status=All&langcode=en
- [ ] Go to benefit "COVID-19 funeral assistance" edit page.

image

- [ ] Input >= 05-20-2020 with space between = and 05
- [ ] Click "Save".

Get following error.

image

- [ ] Input >=5-20-2020 with MM single digit.
- [ ] Click "Save".

Get following error.

image

- [ ] Input <10year without s at the end
- [ ] Click "Save".

Get following error.

image

- [ ] Input >20-12-2020 as invalid date.
- [ ] Click "Save".

Get following error.

image

4. https://github.com/GSA/px-benefit-finder/issues/898

http://localhost/admin/content?combine=Social+Security+disability+insurance+for+spouse&type=bears_benefit&status=All&langcode=en

- [ ] Go to benefit "Social Security disability insurance for spouse" edit page.
- [ ] In Benefit eligibility criteria "Applicant marital status" acceptable values field,
- [ ] Input "Single".

image

- [ ] Click "Save" button.
- [ ] You get following error and cannot save.

The error message includes all the acceptable values of criteria "Applicant marital status".

image

### Requires New Config
- [ ] Yes
- [ ] No

### Requires New Content
- [x] Yes
- [ ] No

visit these paths after code is merged to generate new content from Benefit Finder App, generates new JSON data files
```
/benefit-finder/api/life-event/death/jsonfile
/benefit-finder/api/life-event/retirement/jsonfile
/benefit-finder/api/life-event/disability/jsonfile
/benefit-finder/api/life-event/es_death/jsonfile
/benefit-finder/api/life-event/es_retirement/jsonfile
/benefit-finder/api/life-event/es_disability/jsonfile
```

### Validation Steps
- Test instruction 1
- Test instruction 2
- Test instruction 3

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders
- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions
Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

### CODE REVIEW

**Comment by akf** [comment]
I had to skip testing A11y Improvement 3 -- VoiceOver isn't reading anything out for me on the step indicators other than "Progress: Group, you are currently on a group" ... and although it gave me some instructions on interacting with a group, they don't work. So I think I just don't know how to use VoiceOver and I'm going to trust you on that. 

I noticed, by accident, that if I click or hit Enter on the step indicators, the form submits and I get all the error messages. That doesn't happen on for me on https://www.usa.gov/benefit-finder/death

**Review by akf — COMMENTED** [review]
@scottqueen-bixal I went through this (except for the VoiceOver test I commented on). I see a couple of things in the step indicators that are not specifically called out in your notes and might be bugs: 

First, the steps for "death" are now "Questions 1 of 2" and "Questions 2 of 2": 

Screenshot 2024-03-20 at 5 21 48 PM

Second, the step indicators are now clickable, and the submit the form. (I discovered this by accident while I was trying to figure out how to get VoiceOver to read them to me.) 

Screenshot 2024-03-20 at 5 23 32 PM

So I'm submitting this review as comments-only, and would like to hear from you before I take any action. Thanks!

**Comment by scottqueen-bixal** [comment]
> First, the steps for "death" are now "Questions 1 of 2" and "Questions 2 of 2":
> 
> Screenshot 2024-03-20 at 5 21 48 PM

These values come from the CMS, they are attributed as titles in each section.  The step navigation iterates through the sections to generate the text values for each step.

The updates are likely expected, but will confirm with BF content folks.

**Comment by scottqueen-bixal** [comment]
> Second, the step indicators are now clickable, and the submit the form. (I discovered this by accident while I was trying to figure out how to get VoiceOver to read them to me.)
> 
> Screenshot 2024-03-20 at 5 23 32 PM

The indicators are clickable, and are also that way on prod at the moment.  This form is never really submitted in the traditional sense, but what it does do is act as a navigation to that step.  It has similar functionality to the continue button. If you are getting errors I suspect it is because the required fields had not yet been completed.

Here is a screen capture of what I see on production at the moment



https://github.com/usagov/usagov-2021/assets/37077057/a24f7076-ac71-49b4-98ba-468c35189ec3

**Comment by scottqueen-bixal** [comment]
> I had to skip testing A11y Improvement 3 -- VoiceOver isn't reading anything out for me on the step indicators other than "Progress: Group, you are currently on a group" ... and although it gave me some instructions on interacting with a group, they don't work. So I think I just don't know how to use VoiceOver and I'm going to trust you on that.

I always feel like I don't do voiceover or key interaction good :)

Each tool is a bit different.  On a mac, which is what is demonstrated in the video, I am able to interact with the group by using `Control-Option-Left` or `Control-Option-Right` arrows

**Comment by scottqueen-bixal** [comment]
> First, the steps for "death" are now "Questions 1 of 2" and "Questions 2 of 2":

confirming that this was expected, but there are ongoing changes with that content not reflective of any code changes in this pull request.

> [10:54 AM] Diego Cob
Scott Queen
did you make these updates in content on cms? 📄 Screenshot 2024-03-21 at 10.53.44 AM.png

> Diego: We made them and now we are changing it back to something else as per USAGov's content team suggestion.

**Comment by akf** [comment]
> The indicators are clickable, and are also that way on prod at the moment.

Well, look at that, you're right! Yesterday I was not seeing this behavior on prod, and since prod has not changed, it must have been something I was doing differently.

**Review by akf — APPROVED** [review]

**Pull request merged**
