### PR TITLE
Usagov 1524 widening the site parent branch

### PR DESCRIPTION
**Pull request by YaritzaGarcia**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-1524
https://cm-jira.usa.gov/browse/USAGOV-1469
https://cm-jira.usa.gov/browse/USAGOV-1487
https://cm-jira.usa.gov/browse/USAGOV-1559

## Description

-This includes all things core homepage, including the All topics cards. life events carousel, How do I box. The banner image and welcome message box are automatically linked / aligned with the How do I box so these re all set.
-This includes the header that contains the logo, search box, and language toggle. Also including the official banner left alignment.
- This includes widening the footer and identifier

## Type of Changes

- [ ] New Feature
- [ ] Bugfix
- [x] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

## Testing Instructions

**Homepage changes**

1. Run `bin/drush cr`, `bin/npm run lint`, and `docker compose up`
2. Go to the [homepage](http://localhost/)
3. Check that the homepage look like the following screenshots:
      - 4 cards in the carousel (screen width > 1200px)
image

      - 3 cards in the carousel (screen width < 1200px & screen width > 1024px)
image

      - 2 cards in the carousel (screen width < 1024px & screen width > 640px)
federalist-5e2efa86-bf20-4f68-a5aa-8cfd5db00cb7 sites pages cloud gov_site_yaritzagarcia_wideningsite_ (4)

      - 1 card in the carousel (screen width < 640px)
federalist-5e2efa86-bf20-4f68-a5aa-8cfd5db00cb7 sites pages cloud gov_site_yaritzagarcia_wideningsite_ (5)

Here's a summary of some of the changes you should see.
1. **How do I section**
      - Width of the white background increased to 1124px (for desktop and larger screens, this changes for other screen sizes)
      - Left indent of [first vertical line + link] and How do I header is 48px to match up with the [carousel: left arrow button 40 px and space/padding 8px before first card]. Left of first card edge (2px stroke) should line up with the How do I header and vertical line of the first link in the How do I section.
2. **Life events section**
      - Life events carousel will consist of four cards up 
      - The widest part of the Life events carousel, aligns with the widest part of the How do I section (1124px)
      - The cards have a padding of 16px on each side
      - Arrow buttons are 40px wide 
      - The title of the section aligns with the left side of the first card in desktop and for the rest of the devices it should align with the left side of the prev arrow button.
      - Carousel slide is aprox. 243px wide when the 4 slides are visible but this may vary for other devices. 
3. **All topics grid**
      - Cards are spaced 8px apart from each other
      - Card headers are now in sentence case
      - Dashed line should have a 15px padding on the left and right sides (so that it doesn’t go all the way across)
      - The width of the section is the same as the How do I section (1124px)
      - The title of the section aligns with the left side of the grid in desktop and for the rest of the devices it should align with the Life events title.

**Test primary navigation alignment**
1. Go to http://localhost/ and check that the header elements aligns with the homepage How Do I box, Life Events Carousel, and All topics and services sections

**Test Footer and Identifier**
1. Go to http://localhost/ and check that the footer and identifier aligns with the elements of the homepage and header 
image

### Requires New Config
- [ ] Yes
- [x] No

### Requires New Content
- [ ] Yes
- [x] No

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders
- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions
Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
3. Find the commit of this pull request.
4. Build and deploy the changes.
5. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

### CODE REVIEW

**Comment by IsabelLaurenceau** [comment]
I'm getting an extra Spanish translation button: 
Extra Spanish Button

**Comment by IsabelLaurenceau** [comment]
I'm not sure if this is what you meant for the How Do I header and cards lining up but I think it's slightly off (only could tell with the ruler) 
Cards and Hoiw do I Line Up

**Comment by IsabelLaurenceau** [comment]
I'm only getting a card padding of 8px on each side
Card Padding

**Review by IsabelLaurenceau — CHANGES_REQUESTED** [review]
I put my changes in the comments with screen shots. Let me know if you have any questions on them!

**Comment by YaritzaGarcia** [comment]
> I'm only getting a card padding of 8px on each side Card Padding

Oh, sorry for the confusion. The 8px is correct. I'm going to update the PR description.

**Comment by YaritzaGarcia** [comment]
> I'm getting an extra Spanish translation button: Extra Spanish Button

Run bin/drush cim? I think this is happening due to a change from another ticket.

**Review by IsabelLaurenceau — APPROVED** [review]

**Pull request merged**
