### PR TITLE
Usagov 1548 ceo state and country

### PR DESCRIPTION
**Pull request by IsabelLaurenceau**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-1548

## Description

Changed the name of the input and the autofill type so that users see the correct state when autofilling on Chrome. Check if the browser is Chrome (note this fires and fixes the problem in Edge as well) and only apply changes there. 
Firefox should still default to an empty dropdown and Safari does not autofill at all. 

## Type of Changes

- [ ] New Feature
- [x] Bugfix
- [ ] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

### Change Requirements

- [ ] Requires New Documentation (Link: {})
- [ ] Requires New Config
- [ ] Requires New Content

### Validation Steps

- make sure you have some addresses already saved to Chrome: (chrome://settings/addresses)
- on /elected-officials use the autofill tool from Chrome
- the correct state should show 
- click find my elected officials
- check that the address is correct 
- in Chrome address bar check that the query value for "select-dropdown" is also correct 
-  Check in other browsers (from what I can tell Safari can autofill the other fields but not state) 

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

### CODE REVIEW

**Comment by developer43** [comment]
@IsabelLaurenceau I just did a test and it now shows the state instead of the country in the state list.
Screenshot 2024-09-12 at 3 05 15 PM

**Comment by developer43** [comment]
I can approve just let me know when it's not a work in progress. thanks

**Comment by IsabelLaurenceau** [comment]
Thanks @developer43! I am still seeing some issues on Firefox so I'm keeping this in draft mode for now.

**Review by developer43 — APPROVED** [review]

**Comment by akf** [comment]
@IsabelLaurenceau I'm confused by the status of this PR. It's been approved but not merged into dev, and I was about to merge it, but I see that the Jira ticket says it's DONE -- good in prod! Is this an approach you decided to abandon? 
The PR is approved, so if it should move forward, you can merge it yourself. If it shouldn't move forward, just close it. Thank you!

**Comment by YaritzaGarcia** [comment]
@IsabelLaurenceau Hello! Any updates on this? I see that the ticket says it's done but I want to check if we can close this PR, merge it or wait?

**Comment by developer43** [comment]
Screenshot 2024-10-04 at 1 11 12 PM

**Comment by IsabelLaurenceau** [comment]
Hello, I'm just seeing this, missed it last week. It looks like it got moved to "review on dev" on Jira on the Sep 19th even though it hadn't been merged in yet. The ticket on Jira seemed to have just gone through the conveyor belt while I was out. This did need to be merged in and the approach was not abandon.

**Comment by IsabelLaurenceau** [comment]
Hello, I'm just seeing this, missed it last week. It looks like it got moved to "review on dev" on Jira on the Sep 19th even though it hadn't been merged in yet. The ticket on Jira seemed to have just gone through the conveyor belt while I was out. This did need to be merged in and the approach was not abandon.

**Pull request merged**
