### PR TITLE
USAGOV-1926: PXBF release v0.6.1.beta.1

### PR DESCRIPTION
**Pull request by scottqueen-bixal**
# Benefit Finder Release v0.6.1.beta.1

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-1926

## Related Github Issue

https://github.com/GSA/px-benefit-finder/releases/tag/v0.6.1.beta.1

https://github.com/GSA/px-benefit-finder/milestone/11?closed=1

### Data improvements
[Update crazyegg variable programatically](https://github.com/GSA/px-benefit-finder/issues/1755)	https://github.com/GSA/px-benefit-finder/issues/1755

### Design improvements
[Include all benefits icon](https://github.com/GSA/px-benefit-finder/issues/1739)	https://github.com/GSA/px-benefit-finder/issues/1739
[DESIGN | Update Typography across application](https://github.com/GSA/px-benefit-finder/issues/1445)	https://github.com/GSA/px-benefit-finder/issues/1445

### Application improvements
[Error message not working on date fieldsets with out required flag](https://github.com/GSA/px-benefit-finder/issues/1737)	https://github.com/GSA/px-benefit-finder/issues/1737

### Content improvements
[UX Content Changes](https://github.com/GSA/px-benefit-finder/issues/1662)	https://github.com/GSA/px-benefit-finder/issues/1662

## Type of Changes

- [ ] New Feature
- [x] Bugfix
- [x] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

### Data improvements
[Update crazyegg variable programatically](https://github.com/GSA/px-benefit-finder/issues/1755)	https://github.com/GSA/px-benefit-finder/issues/1755

- [ ] edit death of a loved one spanish/english life event to include the following in the `Header` field

```
<script id="bf-track-by-name" type="text/javascript">
  var CE_SNAPSHOT_NAME = "";
</script>
```

- [ ] navigate to `/death`
- [ ] find script in `<head />` to ensure that it rendered

As you navigate through the app, we expect that the value assigned to CE_SNAPSHOT_NAME updates

this is how we will construct the name in the application

```
<script type="text/javascript">
    var CE_SNAPSHOT_NAME = "{pageView}-{life-event-id}-{desktop || mobile}";
</script>
```

for example

```
<script type="text/javascript">
    var CE_SNAPSHOT_NAME = "bf-form-1-disability-desktop";
</script>
```

So the values would look like this....
```
<!-- desktop values -->

bf-intro-disability-desktop
bf-form-1-disability-desktop
bf-form-2-disability-desktop
bf-form-completion-modal-disability-desktop
bf-verify-selections-disability-desktop
bf-result-eligible-view-disability-desktop
bf-result-not-eligible-view-disability-desktop
```
```
<!-- mobile values -->

bf-intro-disability-mobile
bf-form-1-disability-mobile
bf-form-2-disability-mobile
bf-form-completion-modal-disability-mobile
bf-verify-selections-disability-mobile
bf-result-eligible-view-disability-mobile
bf-result-not-eligible-view-disability-mobile
```

The current know life event ids are as follows,
 
```
death
es_death
 
disability
es_disability
 
retirement
es_retirement
 
all_benefits
es_all_benefits
```

### Design improvements
[Include all benefits icon](https://github.com/GSA/px-benefit-finder/issues/1739)	https://github.com/GSA/px-benefit-finder/issues/1739

- [ ] publish `all_benefits` and `es_all_benefits` nodes
- [ ] Navigate to `admin/content?combine=&type=bears_life_event_form&status=All&langcode=All`
- [ ] Go to life event form "Benefit finder: death of a loved" edit page
- [ ] CLICK "Add Relevant Benefit"

Screenshot 2024-08-28 at 6 43 05 PM

- [ ] Select life event form "Benefit finder: all benefits"
- [ ] Add link "/benefit-finder/all-benefits"
- [ ] CLICK Save to generate JSON files
- [ ] Navigate to life event "Benefit finder: death of a loved one" in draft mode benefit-finder/death?mode=draft
- [ ] Fill form to get into result page
- [ ] Ensure the all benefits icon is displayed in both relative benefits cards

expected:
Screenshot 2024-08-28 at 6 43 05 PM

[DESIGN | Update Typography across application](https://github.com/GSA/px-benefit-finder/issues/1445)	https://github.com/GSA/px-benefit-finder/issues/1445

- [ ] navigate through `/death`

Expected view(s)
screencapture-localhost-benefit-finder-death-2024-08-27-10_10_14

screencapture-localhost-benefit-finder-death-2024-08-27-10_10_35

screencapture-localhost-benefit-finder-death-2024-08-27-10_11_06

Screenshot 2024-08-27 at 10 11 46 AM

screencapture-localhost-benefit-finder-death-2024-08-27-10_11_53

screencapture-localhost-benefit-finder-death-2024-08-27-10_12_13

screencapture-localhost-benefit-finder-death-2024-08-27-10_12_29

screencapture-localhost-benefit-finder-death-2024-08-27-10_12_59

### Application Improvements
[Error message not working on date fieldsets with out required flag](https://github.com/GSA/px-benefit-finder/issues/1737)	https://github.com/GSA/px-benefit-finder/issues/1737

- [x] navigate to `/death`
- [x] CLICK continue without providing any values
- [x] ensure error alert is rendered
- [x] SELECT an option from a fieldset with `<select />` input
- [x] ensure the error is cleared
- [x] SELECT the default option `--Select--`  from the now valid input
- [x] ensure the error is flagged and the DOM updates as expected

expected:

https://github.com/user-attachments/assets/8cc10631-edeb-42d7-b862-a8ec563ec9b9

- [ ] publish `all_benefits` node
- [ ]  navigate to `/all_benefits`
- [ ] on the first step of the form, SELECT a month value from the date fieldset
- [ ] CLICK continue
- [ ] ensure that the error alert is rendered
- [ ] SELECT the default option `--Select--`  from the now invalid input
- [ ] ensure that the error alert is cleared
- [ ] CLICK continue
- [ ] ensure that you can proceed to the next step
- [ ] CLICK back to return to the first step
- [ ] SELECT a month value from the date fieldset
- [ ] CLICK continue
- [ ] ensure that the error alert is rendered
- [ ] SELECT the default option `--Select--`  from the now invalid input
- [ ] ensure that the error alert is cleared
- [ ] enter a day value to the date fieldset
- [ ] CLICK continue
- [ ] ensure that the error alert is rendered

expected:

https://github.com/user-attachments/assets/cb56f5d6-ee52-4f5a-adbb-8c7454cb1469

### Content improvements
[UX Content Changes](https://github.com/GSA/px-benefit-finder/issues/1662)	https://github.com/GSA/px-benefit-finder/issues/1662

Current | Suggested EN | Suggested ES
-- | -- | --
Start | Start finding benefits | Encuentre sus beneficios
Continue | Next | Siguiente
Review selections | Review your selections | Revise sus respuestas
See results | Get your results | Obtenga sus resultados
Close all | Expand all  | Abrir todos 
See benefits you did not qualify for | Explore other potential benefits  | Explore otros beneficios

## Detailed Testing steps

- [ ] navigate application and review content updates

expected:
Screenshot 2024-09-04 at 9 41 29 AM

Screenshot 2024-09-04 at 9 41 56 AM

Screenshot 2024-09-04 at 9 42 39 AM

Screenshot 2024-09-04 at 9 43 18 AM

Screenshot 2024-09-04 at 10 15 49 AM

### Change Requirements

- [ ] Requires New Documentation (Link: {})
- [ ] Requires New Config
- [ ] Requires New Content

### Validation Steps

- Test instruction 1
- Test instruction 2
- Test instruction 3

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

### CODE REVIEW

**Review by gchi25 — APPROVED** [review]
Tested. Worked as expected.

**Comment by akf** [comment]
I've flagged @IsabelLaurenceau to review this tomorrow morning, as I'm swamped.

**Comment by IsabelLaurenceau** [comment]
Good morning! Working on this review. For "Application improvements"-  https://github.com/GSA/px-benefit-finder/issues/1737 can you let me know how to "update proxy url to point at our main bxdev env" please? 

I've reviewed everything else and they all pass!

**Comment by scottqueen-bixal** [comment]
> Good morning! Working on this review. For "Application improvements"- [GSA/px-benefit-finder#1737](https://github.com/GSA/px-benefit-finder/issues/1737) can you let me know how to "update proxy url to point at our main bxdev env" please?
> 
> I've reviewed everything else and they all pass!

@IsabelLaurenceau Looks like some of our local testing steps made it into this PR.

You don't need to perform those, if all_benefits and death life events are published in a recent DB, you should be able to complete the Improvement manual tests.

**Comment by IsabelLaurenceau** [comment]
Hm @scottqueen-bixal the error isn't getting flagged when I put the valid input back to select. It looks like it's doing what your second video shows (8-30 at 10.15.21AM) but I was following the first instructions and expecting what the first video shows (8-30 at 10.08.22AM)  

https://github.com/user-attachments/assets/d83d4c80-5752-45b2-a980-b94ac9799c3b

**Comment by scottqueen-bixal** [comment]
> Hm @scottqueen-bixal the error isn't getting flagged when I put the valid input back to select. It looks like it's doing what your second video shows (8-30 at 10.15.21AM) but I was following the first instructions and expecting what the first video shows (8-30 at 10.08.22AM)
> 
>  Screen.Recording.2024-09-05.at.8.53.06.AM.mov

indeed, that should be handled differently - tracking a bug ticket for a v0.6.2 patch here [Error handling on required fields not persisting with default select options](https://github.com/GSA/px-benefit-finder/issues/1772)	https://github.com/GSA/px-benefit-finder/issues/1772

**Review by IsabelLaurenceau — APPROVED** [review]
Talked with Scott. Will deploy this with a patch 0.6.2 coming later for the one missing error handling piece

**Pull request merged**
