### PR TITLE
usagov-959-duplicate-id: usagov-959-duplicate-id

### PR DESCRIPTION
**Pull request by developer43**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-959

## Description

AMP issue: <button> element has an aria-controls attribute value that includes one or more invalid or duplicate ids. 
Check and make sure the id is no longer in the <button> within the <h2> of the accordion

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Review by akf — CHANGES_REQUESTED** [review]
I have a couple of concerns about this. I'm putting them in the Jira ticket where we can share with Julia.

**Comment by developer43** [comment]
@akf I made the requested change and it's ready for your review. Thanks!

**Review by akf — CHANGES_REQUESTED** [review]
Much better! I have a suggestion -- let's move that "replace" filter into the line where UTitle is defined near the top of the template; then we can just use "UTitle" in these other two places. I think you can tack it on right after "trim." 

It's a small thing, but I think it will reduce mistakes in the future and make the twig template easier to read.

**Review by akf — APPROVED** [review]
Decided to approve this as-is. It's not worth holding it up for my little tweak.

**Pull request merged**
