### PR TITLE
USAGOV-30 - State Directory Content Type

### PR DESCRIPTION
**Pull request by thetypicalprogrammer**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-30

## Checklist for the Developer

- [x] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [x] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [x] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Comment by akf** [comment]
I pulled this and was able to synch the config and look at the content type, which is a good start. It looks like pretty much a copy of the Federal fields right now; needs the state-only fields added and "Offices near you" and "Government branch" deleted. 

There are a few things I recently figured out we should do on the content type's first screen. We can go over that at tomorrow's "shadow."

**Review by akf — COMMENTED** [review]
Looks good, and would be okay to merge, but since we're holding off on merging to dev until next week, let's update the permissions as well. This is something I missed in the Federal content type that was just noticed today. 

To do that, go to Admin -> People -> Permissions. i'm sure we want the permissions on "State Directory Record" to match the ones on "Federal Directory Record" (so search for "Federal" -- most of the permissions are under "Node" but not all of them. Once you've made changes, you can export config. 

I checked in a change myself: I noticed that when I edit a State Directory Record, the "City" field wasn't with the rest of the address fields, so took it upon myself to adjust the order of fields a bit. Also, I enabled the left nav menu (this is in Block Layout).

**Comment by bobert-2** [comment]
> Looks good, and would be okay to merge, but since we're holding off on merging to dev until next week, let's update the permissions as well. This is something I missed in the Federal content type that was just noticed today.
> 
> To do that, go to Admin -> People -> Permissions. i'm sure we want the permissions on "State Directory Record" to match the ones on "Federal Directory Record" (so search for "Federal" -- most of the permissions are under "Node" but not all of them. Once you've made changes, you can export config.
> 
> I checked in a change myself: I noticed that when I edit a State Directory Record, the "City" field wasn't with the rest of the address fields, so took it upon myself to adjust the order of fields a bit. Also, I enabled the left nav menu (this is in Block Layout).

The permissions on the _State Directory Record_ already match all those of the _Federal Directory Record_ so I don't believe any changes are needed. @akf

**Review by bobert-2 — DISMISSED** [review]
Everything looks good to me!

**Review by bobert-2 — DISMISSED** [review]
Nevermind, that's on the other branch. Everything is good to go here ( ᐛ )و

**Review by akf — CHANGES_REQUESTED** [review]
The "Governor" field is supposed to be a link. (I'm looking at a mockup in Trello and this is confirmed in the Directory Record Audit doc.) 

Otherwise I think this is as requested.

**Comment by thetypicalprogrammer** [comment]
Resolved

**Review by akf — COMMENTED** [review]
Sorry I didn't notice earlier, but it looks like changes to config/sync/views.view.locked_content.yml are committed accidentally here. Please revert that. 

Otherwise, all looks good!

**Review by akf — APPROVED** [review]

**Review by akf — CHANGES_REQUESTED** [review]
I clicked a wrong button! Just reiterating that we should remove config/sync/views.view.locked_content.yml from this change. All else looks good!

**Comment by thetypicalprogrammer** [comment]
> I clicked a wrong button! Just reiterating that we should remove config/sync/views.view.locked_content.yml from this change. All else looks good!

Resolved

**Review by akf — APPROVED** [review]
views.view.locked_content.yml is still in here, but it's just a newline-at-end-of-file change, so I'm going to drop my objection. 
Also, I learned what's up with this! Somebody's system saved out this file with the same content, but in a different order, than most of our dev systems want. Dan wants to export it from prod and check in whatever prod wants so he'll stop seeing it listed as a change on deploys -- in fact, I think you probably picked it up in a merge from dev.

**Pull request merged**
