### PR TITLE
USAGOV-1885: Pxbf release v0.6.0.beta.1

### PR DESCRIPTION
**Pull request by scottqueen-bixal**
## Benefit Finder v0.6.0.beta.1
https://github.com/GSA/px-benefit-finder/releases/tag/v0.6.0.beta.1

https://github.com/GSA/px-benefit-finder/milestone/10?closed=1

## Type of Changes

- [x] New Feature
- [x] Bugfix
- [x] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [x] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

### Design Improvements
[DESIGN | Update Icons](https://github.com/GSA/px-benefit-finder/issues/1447)	https://github.com/GSA/px-benefit-finder/issues/1447
[DESIGN | Update Relative Events CTA Cards](https://github.com/GSA/px-benefit-finder/issues/1448)	https://github.com/GSA/px-benefit-finder/issues/1448
[DESIGN | Update Accordion(s) styles](https://github.com/GSA/px-benefit-finder/issues/1449)	https://github.com/GSA/px-benefit-finder/issues/1449
[DESIGN | Update Layout Values](https://github.com/GSA/px-benefit-finder/issues/1451)	https://github.com/GSA/px-benefit-finder/issues/1451
[Redesign | Colors](https://github.com/GSA/px-benefit-finder/issues/1629)	https://github.com/GSA/px-benefit-finder/issues/1629
[Redesign | Buttons Pt1](https://github.com/GSA/px-benefit-finder/issues/1632)	https://github.com/GSA/px-benefit-finder/issues/1632
[Redesign | Buttons Pt2](https://github.com/GSA/px-benefit-finder/issues/1633)	https://github.com/GSA/px-benefit-finder/issues/1633
[Redesign | Italicize Step Indicator](https://github.com/GSA/px-benefit-finder/issues/1661)	https://github.com/GSA/px-benefit-finder/issues/1661
[Redesign |  Step List](https://github.com/GSA/px-benefit-finder/issues/1656)

### Application Improvements
[Adopting GSA's Error Identification](https://github.com/GSA/px-benefit-finder/issues/1121)	https://github.com/GSA/px-benefit-finder/issues/1121
[Error Alert Design Updates](https://github.com/GSA/px-benefit-finder/issues/1643)	https://github.com/GSA/px-benefit-finder/issues/1643
[Include additional text to resolve form field errors with fields](https://github.com/GSA/px-benefit-finder/issues/1513)	https://github.com/GSA/px-benefit-finder/issues/1513
[Include a list of links to the fields that have errors in alerts](https://github.com/GSA/px-benefit-finder/issues/1512)	https://github.com/GSA/px-benefit-finder/issues/1512
[Include error count in alert](https://github.com/GSA/px-benefit-finder/issues/1511)	https://github.com/GSA/px-benefit-finder/issues/1511
[update package version and dependencies](https://github.com/GSA/px-benefit-finder/issues/1687)	https://github.com/GSA/px-benefit-finder/issues/1687
[date field in memorable date doesn't recognize value 0 as error](https://github.com/GSA/px-benefit-finder/issues/1676)	https://github.com/GSA/px-benefit-finder/issues/1676

### Data Layer Improvements

[Create data layer event(s) to track error messages in analytics](https://github.com/GSA/px-benefit-finder/issues/1501)	https://github.com/GSA/px-benefit-finder/issues/1501

### Content Improvements

[Change "Click to select" in SP combo box](https://github.com/GSA/px-benefit-finder/issues/1043)	https://github.com/GSA/px-benefit-finder/issues/1043
[Determine consistent translation for inline field errors](https://github.com/GSA/px-benefit-finder/issues/1555)	https://github.com/GSA/px-benefit-finder/issues/1555

### Custom Module Improvements
[Error Label Content Override](https://github.com/GSA/px-benefit-finder/issues/1614)	https://github.com/GSA/px-benefit-finder/issues/1614
[Hide qualtrics survey, with exceptions](https://github.com/GSA/px-benefit-finder/issues/1701)	https://github.com/GSA/px-benefit-finder/issues/1701
[Benefit finder page level surveys](https://github.com/GSA/px-benefit-finder/issues/1638)	https://github.com/GSA/px-benefit-finder/issues/1638
[Add search title in JSON data](https://github.com/GSA/px-benefit-finder/issues/1674)	https://github.com/GSA/px-benefit-finder/issues/1674

## Design Improvements

- [ ] navigate the app and identify these design updates

[DESIGN | Update Icons](https://github.com/GSA/px-benefit-finder/issues/1447)	https://github.com/GSA/px-benefit-finder/issues/1447

expected:
Screenshot 2024-08-20 at 2 22 03 PM

[DESIGN | Update Relative Events CTA Cards](https://github.com/GSA/px-benefit-finder/issues/1448)	https://github.com/GSA/px-benefit-finder/issues/1448

expected:
Screenshot 2024-08-20 at 2 22 00 PM

[DESIGN | Update Accordion(s) styles](https://github.com/GSA/px-benefit-finder/issues/1449)	https://github.com/GSA/px-benefit-finder/issues/1449

expected:
Screenshot 2024-08-20 at 2 22 26 PM

[Redesign | Buttons Pt1](https://github.com/GSA/px-benefit-finder/issues/1632)	https://github.com/GSA/px-benefit-finder/issues/1632

[Redesign | Buttons Pt2](https://github.com/GSA/px-benefit-finder/issues/1633)	https://github.com/GSA/px-benefit-finder/issues/1633

Screenshot 2024-08-20 at 2 21 25 PM

[Redesign | Italicize Step Indicator](https://github.com/GSA/px-benefit-finder/issues/1661)	https://github.com/GSA/px-benefit-finder/issues/1661

Screenshot 2024-08-20 at 2 21 15 PM

[Redesign |  Step List](https://github.com/GSA/px-benefit-finder/issues/1656)
Screenshot 2024-08-20 at 2 20 44 PM

## Application Improvements

[Hide qualtrics survey, with exceptions](https://github.com/GSA/px-benefit-finder/issues/1701)	https://github.com/GSA/px-benefit-finder/issues/1701

- [x] ensure on page load that the survey `div` is in the DOM, `bf-qual-survey` with the `hidden` attribute is `true`
- [x] navigate to results view
- [x] ensure on page load that the survey `div` is in the DOM, `bf-qual-survey` with the `hidden` attribute is `false`

[update package version and dependencies](https://github.com/GSA/px-benefit-finder/issues/1687)	https://github.com/GSA/px-benefit-finder/issues/1687

- [x] navigate to `/death`
- [x] inspect DOM
- [x] search for `data-version`
- [x] ensure version is `0.6.0.beta.1`

[date field in memorable date doesn't recognize value 0 as error](https://github.com/GSA/px-benefit-finder/issues/1676)	https://github.com/GSA/px-benefit-finder/issues/1676

- [x] navigate to /death
- [x] in the first step of the form, input 0 for the date field value of the first question
- [x] CLICK Continue
- [x] ensure that the day value indicates an error

[Error Alert Design Updates](https://github.com/GSA/px-benefit-finder/issues/1643)	https://github.com/GSA/px-benefit-finder/issues/1643
- [x] navigate to `/death`
- [x] CLICK start
- [x] without completing any fields, CLICK `Continue`
- [x] ensure new styling  and layout for error alerts 

expected:
Screenshot 2024-08-08 at 10 13 18 AM

[Include error count in alert](https://github.com/GSA/px-benefit-finder/issues/1511)	https://github.com/GSA/px-benefit-finder/issues/1511
[Include a list of links to the fields that have errors in alerts](https://github.com/GSA/px-benefit-finder/issues/1512)	https://github.com/GSA/px-benefit-finder/issues/1512
[Include additional text to resolve form field errors with fields](https://github.com/GSA/px-benefit-finder/issues/1513)	https://github.com/GSA/px-benefit-finder/issues/1513
[Determine consistent translation for inline field errors](https://github.com/GSA/px-benefit-finder/issues/1555)	https://github.com/GSA/px-benefit-finder/issues/1555

- [x] ensure the number of errors indicated in the alert is equal to the number of inputs/selects that have errors

Screenshot 2024-08-01 at 3 57 19 PM

- [x] ensure that the error banner has a list of error descriptions, which are links to each of the error fields

Screenshot 2024-08-01 at 3 57 15 PM

- [x] ensure that selecting the error link takes you to the field described and focus that field
- [x] ensure the fields with errors have red borders around them
- [x] ensure each error fieldset should have an accompanying `bf-error-detail` field that indicates to the user to "fill out the {legend} field"

Expected:
en locale
Screenshot 2024-08-01 at 3 56 29 PM

- [x] ensure that when you resolve this error the error border is removed
- [x] ensure that when all fields in a field group are resolved the error border on the `<fieldset />` is removed
- [x] ensure that when you resolve an error the error description is removed from the error banner list
- [x] ensure that when you resolve an error the error count decreases
- [x] ensure that when all errors are resolved all error indicators are removed

### Content Improvements

[Change "Click to select" in SP combo box](https://github.com/GSA/px-benefit-finder/issues/1043)	https://github.com/GSA/px-benefit-finder/issues/1043

- [ ] navigate to `/death`
- [ ] CLICK start to navigate to first step of form
- [ ] confirm that the `<select/>`'s have the following default labels and configuration

en
```JSON
  "select": {
    "labelSelect": "Select an option",
    "defaultValue": "-Select-",
    ...
  },
```

### Data Improvements

[Create data layer event(s) to track error messages in analytics](https://github.com/GSA/px-benefit-finder/issues/1501)	https://github.com/GSA/px-benefit-finder/issues/1501

- [x] navigate to `/death`
- [x] CLICK continue without providing field values
- [x] confirm error banner is visible
- [x] console.log(window.dataLayer)
- [x] confirm `bf_form_page_submit_attempt` is in the dataLayer
- [x] confirm the event has a string of errors, that are the ids of the field values with errors
- [x] confirm the error count matches that presented in the UI
- [x] confirm that formSuccess is `false`

expected structure:
```JSON
{
    "event": "bf_form_page_submit_attempt",
    "bfData": {
        "errors": "STRING, STRING, STRING,...",
        "errorCount": {
            "number": NUMBER,
            "string": "STRING"
        },
        "formSuccess": false
    }
}
```

- [x] resolve errors by providing values for required fields
- [x] CLICK `Continue`
- [x] console.log(window.dataLayer)
- [x] confirm a second `bf_form_page_submit_attempt` is in the dataLayer
- [x] confirm the event has an _empty_ string of errors
- [x] confirm the error count is `0`
- [x] confirm that formSuccess is `true`

expected structure:
```JSON
{
    "event": "bf_form_page_submit_attempt",
    "bfData": {
        "errors": "",
        "errorCount": {
            "number": NUMBER,
            "string": "STRING"
        },
        "formSuccess": true
    }
}
```

### Custom Module Improvements

[Error Label Content Override](https://github.com/GSA/px-benefit-finder/issues/1614)	https://github.com/GSA/px-benefit-finder/issues/1614

- [x] Navigate to `admin/content?combine=&type=bears_life_event_form&status=All&langcode=All`
- [x] Go to life event form "Benefit finder: death of a loved one" edit page
- [x] Add "Input the date of birth" in `Error Message` field

- [x] Save as published
- [x] Navigate to `benefit-finder/api/life-event/death`
- [x] Verify errorMessage "Input the date of birth"

[Add search title in JSON data](https://github.com/GSA/px-benefit-finder/issues/1674)	https://github.com/GSA/px-benefit-finder/issues/1674

- [x] Navigate to `admin/content?combine=&type=bears_life_event&status=All&langcode=All`
- [x] Go to life event "Benefit finder: retirement" edit page
- [x] Add "Approaching retirement" in search title field
- [ ] Save as published
- [ ] Go to life event "Benefit finder: disability" edit page
- [ ] Add "Living with a disability or illness" in search title field
- [ ] Save as published
- [ ] Navigate to `benefit-finder/api/life-event/death`
- [x] Verify searchTitle in json data

image

- [x] Navigate to `benefit-finder/api/life-event/death/jsonfile` to generate JSON file

after generating json
- [x] navigate to "/benefit-finder/death`
- [x] complete required fields to get to Results view
- [x] ensure updated searchTitles are rendering in Relevant Benefits Cards

Screenshot 2024-08-20 at 10 44 51 AM

### Change Requirements

- [ ] Requires New Documentation (Link: {})
- [ ] Requires New Config
- [ ] Requires New Content

### Validation Steps

- Test instruction 1
- Test instruction 2
- Test instruction 3

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

### CODE REVIEW

**Review by gchi25 — DISMISSED** [review]

**Comment by akf** [comment]
I'm getting an error message when I attempt to import configuration. I think you might have forgotten to include field.storage.paragraph.field_b_error_message.yml: 

> The import failed due to the following reasons:                                                                                                                
>   Configuration <em class="placeholder">field.field.paragraph.b_levent_elg_criteria.field_b_error_message</em> depends on the <em class="placeholder">field.storage.paragraph.field_b_error_message</em> configuration that will not exist after import.

**Comment by scottqueen-bixal** [comment]
> I'm getting an error message when I attempt to import configuration. I think you might have forgotten to include field.storage.paragraph.field_b_error_message.yml:
> 
> > The import failed due to the following reasons:
> > Configuration _field.field.paragraph.b_levent_elg_criteria.field_b_error_message_ depends on the _field.storage.paragraph.field_b_error_message_ configuration that will not exist after import.

Thanks @akf - I've included the missing storage config. I'll have @gchi25 check a few of these items again, but hopefully that resolves the import error you are getting.

**Comment by akf** [comment]
> Thanks @akf - I've included the missing storage config. I'll have @gchi25 check a few of these items again, but hopefully that resolves the import error you are getting.

Yes @scottqueen-bixal, it does!

**Review by akf — APPROVED** [review]
All looks good to me. Since @gchi25 is going to take another look, I won't merge it -- but feel free to do that when you're ready!

**Review by gchi25 — APPROVED** [review]

**Pull request merged**
