### PR TITLE
USAGOV-480-update-composer-lock: Update composer.lock

### PR DESCRIPTION
**Pull request by ghost**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-480

## Checklist for the Developer

- [ x] A link to the JIRA ticket has been added above.
- [x ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [x ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Comment by IsabelLaurenceau** [comment]
So question I wanted to check is the acceptance criteria that it just builds and still works or that the composer lock file is updated? Because I'm still getting the "Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`."

**Comment by ghost** [comment]
Hi @IsabelLaurenceau  
That is odd - let me check on this and I will get back to you on Friday

**Comment by ghost** [comment]
@IsabelLaurenceau  - I figured out the issue, and pushed a one-line change to fix it.

Originally, I removed the content-hash change, to help prevent potential merge conflicts.  However, in doing that I removed composers method of quickly checking if the files are in sync.   Since we are not frequently updating composer.lock, the merge conflict thing should not be an issue for this project though.

The message should be gone now, as I allowed composer update to make the change to the content-hash.

**Review by IsabelLaurenceau — APPROVED** [review]
Works correctly now with no warning messages anymore!

**Pull request merged**
