### PR TITLE
Usagov 394 telephone number for mobile

### PR DESCRIPTION
**Pull request by IsabelLaurenceau**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-394

## Description

Files changed:

- web/themes/custom/usagov/scripts/telephoneForMobileNode.js
- web/themes/custom/usagov/templates/node--directory-record--full.html.twig
- web/themes/custom/usagov/templates/views-view-fields--federal-agencies.html.twig

Testing:
** Flush all caches
** May need to run bin/gulp build to rebuild theme if changes not evident?
** If no directory exists create one with phone numbers

On /agency-index open accordion

1. On desktop phone number should display same line and as plain text (no href to telephone or underline style) 
2. If multiple phone numbers were put only first should show 
3. Shrink window to <480 to simulate mobile
4. Refresh
5. Phone number should show as a clickable <a>. If you put a description only the phone number should be clickable description should be plain text 
6. Select more info

On /agencies/{your-agency-name-here}

1. On desktop phone number should display same line and as plain text (no href to telephone or underline style) 
2. If multiple phone numbers were put all should show on their own bulleted line
3. Shrink window to <480 to simulate mobile
4. Refresh
5. Phone number should show as a clickable <a>. If you put a description only the phone number should be clickable description should be plain text

## Checklist for the Developer

- [x] A link to the JIRA ticket has been added above.
- [x] The JIRA ticket identifies the desired result of this change.
- [x] The JIRA ticket contains clear acceptance criteria.
- [x] The JIRA ticket contains clear testing steps.
- [x] The JIRA ticket contains a description of "Done".
- [x] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [x] The branch name of this PR matches the project standards.
- [x] QA steps are followed and any changes to process are updated in the ticket.
- [x] Code Standards are followed, there are no bad practices in use.
- [x] Config changes (if any) include only necessary changes.
- [x] No errors in Drupal or Client Browser.
- [x] Code has been tested locally (if possible).
- [x] Following AC and Testing Steps verify changes work as expected.
- [x] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Review by akf — CHANGES_REQUESTED** [review]
This seems to be working on /agency-index. We also want it to work on the Federal Directory Record and State Directory Record pages. (Further, we want to do the same thing throughout the site, so if you can associate this behavior with the "Telephone number" field type, rather than with a specific page or content type, all the better. ) 

I think this is something we talked about but didn't write down. 

Both types of directory records have phone fields for Phone Number, Toll-free Number, and TTY Number.

**Comment by IsabelLaurenceau** [comment]
Hey Amy, You definitely did write it down so it's on me if it isn't working. 
I thought I had addressed it with the last push but I will go through and debug tomorrow morning!

**Comment by IsabelLaurenceau** [comment]
Found the bug. Used querySelector instead of querySelectorAll and in my previous test I only had one phone number.

**Review by akf — CHANGES_REQUESTED** [review]
I've run into a new problem here; it shows up on the detail page: if a phone number field has multiple entries, they're all winding up strung together with only spaces between them. Previously, they were being output as unordered lists if multiple, and paragraphs (I think) if single. 

The trick would be to get the phoneNumberField class applied just to an element around a single phone number ... which would mean modifying fields.field_phone_number.content, and I think there might be something tricky going on there ...

**Review by akf — APPROVED** [review]
Looks great!

**Pull request merged**
