### PR TITLE
Usagov 646 separate custom field

### PR DESCRIPTION
**Pull request by akf**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-646

## Description

Draft concept -- instead of overriding the entire Body field, adds a "Custom Twig Content" checkbox. If checked, a custom twig file will be rendered immediately after any Body content. 

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Comment by IsabelLaurenceau** [comment]
Referring to your comment in the other PR "the only thing I stumbled over was getting the content to not display if the "Custom Twig Content" checkbox wasn't checked." --- were you able to sort this out? Because the content looks to be properly hiding and showing with the check.

**Comment by IsabelLaurenceau** [comment]
I also like the fact that with this, if the box is checked and there is no twig file an error is not thrown. However I am wondering how to safeguard or make sure that the box is checked when needed. Right now I see that /elected-officials & /states should have them because they are forms. I may be overthinking it.

**Comment by IsabelLaurenceau** [comment]
Okay I think using this new field is a good approach for this. The only thing I am seeing is that we need to include one outer div in the twig files with classes "body-copy" and "usa-prose" for styling. 
To keep working on this do you think I should merge your branch into mine or just fork a branch from this and work from there?

**Comment by akf** [comment]
Merging this branch into yours probably makes sense. 
I did work out the checkbox issue -- it's a line in the theme hook that explicitly checks the value of the checkbox.

**Pull request closed without merging**
