### PR TITLE
Usagov 694 life events new name

### PR DESCRIPTION
**Pull request by IsabelLaurenceau**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-694

## Description

Changing "Life experiences" on the homepage to "Life events" and updating the link to point to /life-events.
Enables the redirect module.

### Testing
1. On /life-experiences change the URL alias to /life-events
2. Under URL redirects click Add URL redirect
3. In Path add /life-experiences
4. In To add /life-events
5. Save 
6. Test that localhost/life-experiences redirects to /life-events

## Checklist for the Developer

- [x] A link to the JIRA ticket has been added above.
- [x] The JIRA ticket identifies the desired result of this change.
- [x] The JIRA ticket contains clear acceptance criteria.
- [x] The JIRA ticket contains clear testing steps.
- [x] The JIRA ticket contains a description of "Done".
- [x] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Review by akf — COMMENTED** [review]
I've tried it out and it's looking good so far. Running Tome now to see whether we get something there; I'll report back tomorrow. 
We might want to use/recommend using entity references rather than paths for the redirect target. I found that if I do that (that is, type in "Life Events" and select the match), the redirect appears when I go back to edit the Life Events page, whereas if I just type "/life-events", it doesn't. 
I'm curious whether choosing a language for the redirect actually does anything?

**Review by akf — COMMENTED** [review]
Do you have changes to config/sync/core.entity_form_display.node.basic_page.default that aren't checked in or weren't exported, by chance? I see differences between what's on the file system and what's "active" on my local dev now, and they look like they're related to the redirects. I suspect enabling the module added them, so there's a bit of a chicken-and-egg thing happening. 

I'm also seeing a stubborn difference in views.view.redirect, in that my system wants to put things in a different order than yours did. Neither is "wrong," but it would be nice to know why. Probably not worth spending time on, though. If we keep seeing it as a difference when we deploy, we'll update it from a different system!

**Comment by IsabelLaurenceau** [comment]
Updated! I think it may have had to do that I changed those files for the custom fields branch so when we updated from dev there was an inconsistency? The reason why I'm thinking that is because on that branch I did change the order of somethings (such as moving hide page intro under page intro). I'm not 100% sure because I don't see how it was working without them but anywho the config files are updated and pushed.

**Comment by akf** [comment]
Yep, that took care of the inconsistencies! The redirect module must have added the changes for a basic page automatically, because I saw them as updated on my site but they weren't committed. I didn't get the wizard page changes though, maybe because I didn't edit a wizard page. 

Tome created an HTML file for life-experiences with a meta redirect to life-events, so that's working too.

**Review by akf — APPROVED** [review]

**Pull request merged**
