### PR TITLE
Usagov 1085 content lock

### PR DESCRIPTION
**Pull request by YaritzaGarcia**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-1085

## Description

I enable a module that works as an extension for the module we already have. With this module we now have a configuration that allows us to configure a Lock timeout (in minutes) so that if the page lock reaches that time limit and the person locking that content is not working on the page, it will automatically break the lock. 
Module settings: http://localhost/admin/config/content/content_lock/timeout

## Type of Changes

- [x] New Feature
- [ ] Bugfix
- [ ] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [x] Drupal Config (requires "drush cim")
- [x] New Modules (requires rebuild)
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

## Testing Instructions

1. Run your Docker container as usual.
2. Open http://localhost/user/login in two different browsers. Example: Google Chrome and Safari.
3. Log in to two different accounts, one should be a Site Admin and the other a Content Administrator, one account on each browser.
4. On the Site Admin account, go to this page http://localhost/admin/config/content/content_lock/timeout and change the "Lock Timeout" to 1 minute, or whatever amount of time works best for you.
5. Click "Save Settings" and flush all caches on both accounts.
6. In one of the accounts, go to any page on the website and click edit to lock the content. Example: http://localhost/node/1/edit.
7. Go to the other account and try editing the same page. A message like this should appear on the screen:
image
8. In the same account that you used in the previous step, refresh the page as soon as the time you set in the configuration expires. A message like this should appear on the screen: 
image
9. Try this with one or two more pages.

### Requires New Config
- [x] Yes
- [ ] No

### Requires New Content
- [ ] Yes
- [x] No

### Validation Steps
- Content Administrator, or any other account with permissions, should be able to edit a page if it has not been edited for the amount of time specified in the settings. The time that will be used now is 24 hours (1440 minutes).

## Security Review

- [x] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders
- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions
Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
11. Find the commit of this pull request.
12. Build and deploy the changes.
13. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

### CODE REVIEW

**Review by IsabelLaurenceau — COMMENTED** [review]
I'm not marking it as request changes because I'm honestly unsure if maybe I did something incorrect, but I wasn't getting the last screen you had after the timer ran out (I set my time for one minute) 
Screenshot 2023-10-12 at 3 51 56 PM

**Comment by IsabelLaurenceau** [comment]
Note in case someone gets to this before I'm back Monday: @YaritzaGarcia and I met and the little checkbox "Break stale locks on edit" needs to be selected. She's looking to see if she can save that as the default.

**Comment by YaritzaGarcia** [comment]
> Note in case someone gets to this before I'm back Monday: @YaritzaGarcia and I met and the little checkbox "Break stale locks on edit" needs to be selected. She's looking to see if she can save that as the default.

I just checked this and it is part of the "content_lock_timeout.settings.yml". The "Break stale locks on edit" checkbox is selected on my side. I unchecked the checkbox, ran "bin/drush cim" and changed the value of content_lock_timeout_on_edit. Based on this the configuration is correct in the PR. I would appreciate if someone could try this again, make sure to run "bin/drush cim".

**Review by IsabelLaurenceau — APPROVED** [review]
Works! 
Screenshot 2023-10-16 at 12 44 52 PM

**Pull request merged**
