### PR TITLE
USAGOV-266-fix-aws-sync: add --size-only to stop uploading unchanged files

### PR DESCRIPTION
**Pull request by jacobaaronyeager**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-266

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Review by akf — CHANGES_REQUESTED** [review]
I don't think this is a good idea. I hope Dan is wrong about "aws s3 sync" only using file sizes and not hashes to detect changes on Linux, because I can think of a lot of ways an HTML file might be changed without changing its size! 

What might be a good idea is to change this line a bit further up: 

cp -R /var/www/html/* $RENDER_DIR

to 

cp -Rp /var/www/html/* $RENDER_DIR

... which will maintain modification time. We would still be refreshing all the timestamps when we deploy.

**Comment by akf** [comment]
Following up, what documentation I've found says that aws s3 sync uses file size and timestamp (not md5 hash), and this isn't just a linux thing, it's how the aws s3 sync command works.

**Comment by akf** [comment]
One more thing -- we could stand to add the "-p" flag to all of the cp (not aws s3 cp) commands in tome-sync.sh.

**Comment by jacobaaronyeager** [comment]
@akf Updated

**Review by akf — APPROVED** [review]
This looks entirely safe to me.

**Pull request merged**
