### PR TITLE
USAGOV-607: slash after /es

### PR DESCRIPTION
**Pull request by akf**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-607

## Description

Analytics wants us to link to "/es/", not "/es". This adds a PagerPathSubscriber that is invoked during Tome static site generation; it looks for anchor markup with href="/es" or "/es?[something]" and inserts the trailing slash. 

You can test this on local dev by running static site generation just long enough to generate the index.html page. That page already has a link to "/es" (in the language toggle); you can add '<a href="/es?foo=bar">test link</a>' to the Body of the home page to get an example of the latter form. 

To test: 
* Empty your html directory
* Clear all caches. 
* Navigate to /admin/config/tome/static/generate in the CMS and submit the form
* Look for an index.html file in the html directory. When it exists, you can inspect the result. 

Believe it or not, this seemed like the easiest way. 

The change to usa_twig_vars.module eliminates a warning message I noticed while working on this. 

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Comment by IsabelLaurenceau** [comment]
I'm not sure if this is what we wanted or not. Line 9 in the generated index.html file becomes "href="http://127.0.0.1/es//" 
The double ending // is what I am not sure about.
Line 177 becomes `<a href="/es/" class="language-link" hreflang="es">Español</a>`

**Comment by akf** [comment]
That is not what we want! Thank you for checking and calling this out. (It's also not what I was seeing ... frustrating.)

**Comment by akf** [comment]
So, my previous work to append / to the "alternate" link for /es looked great in the CMS, but two // were being appended for the static site. Honestly I'm not sure why, because that code explicitly checks for an existing /, and the PagerPathSubscriber is only looking at anchors, not <link tags ... I think. But I took the bit of code for the "alternate" link out and I'm getting the right canonical and alternate URLs, as well as the href re-writing within the page. 

I will have to double-check this result on dev when it gets there, but please check it out!

**Comment by akf** [comment]
Er, someone should check it out. I remember you're out tomorrow, @IsabelLaurenceau !

**Review by ghost — APPROVED** [review]
Approved

**Pull request merged**
