### PR TITLE
Usagov-432: state directory import

### PR DESCRIPTION
**Pull request by akf**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-432

## Description

Updates the states_import_prep.php script to use a transformation from Title to path alias that matches up with what mothership did. Also adds a script for creating a mapping between English and Spanish records (although this did not work well for states). 

This is what I used to generate a CSV file to import states into beta. 

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Comment by IsabelLaurenceau** [comment]
I think we need to change to link that the content generates as well but I'm not sure where. For example I'm seeing now that california is accessible via http://localhost/states/california but not http://localhost/state-governments/california

**Comment by akf** [comment]
The state pages are still supposed to have /states/state_name paths!

**Comment by IsabelLaurenceau** [comment]
On ticket [799](https://cm-jira.usa.gov/browse/USAGOV-799) said it should be state-government/alabama

**Comment by akf** [comment]
Joanne confirmed that was a typo on USAGOV-799. It's still supposed to be /states/alabama

**Review by IsabelLaurenceau — APPROVED** [review]

**Pull request merged**
