### PR TITLE
USAGOV-191-enable-opcache

### PR DESCRIPTION
**Pull request by jacobaaronyeager**
## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-191

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

### CODE REVIEW

**Comment by jacobaaronyeager** [comment]
I can't find any reason to not have opcache enabled on local, so I'm just turning it on.

**Review by akf — CHANGES_REQUESTED** [review]
Okay, it looks like we *do* need to turn this off on locals. The problem with opcache on a developer's system is that it caches php code (at a level below drupal's caches), so the developer would have to restart php each time they make a code change if they want to see the result. 

Here's what I came up with as a simple change to see whether caching would break my developer flow: 

1. Load the home page and view source. Look for `<meta name="description"` -- we populate a string for that value via the usa_twig_vars module. 

2. After line 80 of web/modules/custom/usa_twig_vars/usa_twig_vars.module, add a line overwriting the value of `$usa_twig_vars['meta_description']` like so: 

```
          $usa_twig_vars['meta_description'] = usa_twig_vars_get_meta_description($node);
          $usa_twig_vars['meta_description'] = 'WE ARE HERE';
```
3. Re-load the home page and observe the value in `<meta name="description"`. With opcache disabled, it will show "WE ARE HERE" (maybe you need to do a hard refresh, maybe not). With it enabled, it will still show the original text and no amount of cache clearing will change it.

**Review by akf — CHANGES_REQUESTED** [review]
Not quite there yet. I learned a bit testing this, and I will share! All testing was local. 

First, I ran bin/bootstrap. I saw the message "OPCache is already disabled.", which makes sense because I had built my site with code that specified that by default. 

Next, I shut down my docker containers, ran "docker system prune --all," and ran bin/init. I then checked /etc/php8/php.ini on my cms container, and found that it had both opcache.enable and opcache.enable_cli set to 1.

Thinking that bin/init hadn't run bootstrap (I am unsure about this; local dev CMS container has CF_INSTANCE_INDEX set to 1 and bin/bootstrap says it would run automatically only when CF_INSTANCE_INDEX is 0), I ran bin/bootstrap. And I saw this message: 

```
Disabling OPCache...
/var/www/scripts/bootstrap.sh: line 145: sudo: not found
OPCache disabled.
```

That last line is a LIE, opcache.enable and opcache.enable_cli are still set to 1! 

I think we should turn off opcache.enable_cli as well as opcache.enable. 

CF_INSTANCE_INDEX is set to 1 in docker-compose.yml. Looks like it's been that way a long time; my guess would be it's intentional so we don't run tome automatically, but I'm just guessing.

**Comment by jacobaaronyeager** [comment]
updated and tested.  let me know if there is something that doesn't work

**Comment by akf** [comment]
Looking much better. After pruning all my images and running bin/init I have this in php.ini: 

```
opcache.enable=0
opcache.enable_cli = 1
```

Do you think we should turn off opcache.enable_cli on local dev as well?

**Review by akf — APPROVED** [review]
Looks good. I now have this locally: 

```
opcache.enable=0
opcache.enable_cli=0
```

**Pull request merged**
